import { chromium } from '@playwright/test';
const OUT = '/tmp/claude-1001/-data-zac-zac-development-snorlax/a0426196-e872-4bb8-aaaf-fdbce58bb28b/scratchpad';
const b = await chromium.launch();
const p = await b.newPage({ viewport: { width: 1440, height: 1000 } });
await p.goto('http://localhost:3111/', { waitUntil: 'networkidle' });
await p.screenshot({ path: `${OUT}/v2-hero.png` });
// mid-page: diagnosis + steps
await p.evaluate(() => document.querySelector('.diagnosis')?.scrollIntoView());
await p.waitForTimeout(400);
await p.screenshot({ path: `${OUT}/v2-diagnosis.png` });
await p.evaluate(() => document.querySelector('.split')?.scrollIntoView());
await p.waitForTimeout(400);
await p.screenshot({ path: `${OUT}/v2-split.png` });
await p.evaluate(() => document.querySelectorAll('details').forEach(d => d.open = true));
await p.waitForTimeout(500);
await p.screenshot({ path: `${OUT}/v2-full.png`, fullPage: true });
const p2 = await b.newPage({ viewport: { width: 420, height: 900 } });
await p2.goto('http://localhost:3111/', { waitUntil: 'networkidle' });
console.log('mobile overflow:', await p2.evaluate(() => document.documentElement.scrollWidth > document.documentElement.clientWidth));
await p2.screenshot({ path: `${OUT}/v2-mobile.png`, fullPage: true });
await b.close();
