packages:
  - 'apps/*'
  - 'packages/*'

storeDir: .pnpm-store
virtualStoreDir: .pnpm

overrides:
  google-auth-library: 10.7.0

onlyBuiltDependencies:
  - '@sentry/cli'
  - core-js
  - electron
  - esbuild
  - sharp
  - unrs-resolver

allowBuilds:
  '@sentry/cli': true
  core-js: true
  electron: true
  electron-winstaller: false
  esbuild: true
  sharp: true
  unrs-resolver: true
