//! Built-in bulk domain blocklists (nsfw, shopping, social, gambling, press, games, sports,
//! forums, webemail, blog, streaming), embedded at compile time so every packaging path
//! (electron-builder on Windows/macOS, the Linux .deb, and the NixOS flake that builds this
//! crate from source) ships them with zero extra staging steps. The source `.txt` files are
//! regenerated by `scripts/update-blocklists.mjs`, which normalizes every upstream source down
//! to registrable (eTLD+1) domains before writing them here.
//!
//! Matching is intentionally exact-domain-or-`www.` only, NOT the subdomain-wildcard semantics
//! `policy_match::host_matches` uses for user-authored `blockedDomains`. These lists are bulk
//! community/registrable-domain data — wildcard-matching would collaterally block unrelated
//! services hosted under the same apex, e.g. blocking "shopping" must not also block
//! `console.aws.amazon.com` / `signin.aws.amazon.com` just because they are subdomains of
//! `amazon.com`.

use std::collections::{HashMap, HashSet};
use std::sync::OnceLock;

use crate::policy::PremadeListId;

/// One `include_str!` per shipped list — Rust can't loop over a macro, so this is the one place
/// that stays a fixed-size table as new categories are added.
const LISTS: &[(PremadeListId, &str)] = &[
    (
        PremadeListId::Nsfw,
        include_str!("../resources/premade-lists/nsfw.txt"),
    ),
    (
        PremadeListId::Shopping,
        include_str!("../resources/premade-lists/shopping.txt"),
    ),
    (
        PremadeListId::Social,
        include_str!("../resources/premade-lists/social.txt"),
    ),
    (
        PremadeListId::Gambling,
        include_str!("../resources/premade-lists/gambling.txt"),
    ),
    (
        PremadeListId::Press,
        include_str!("../resources/premade-lists/press.txt"),
    ),
    (
        PremadeListId::Games,
        include_str!("../resources/premade-lists/games.txt"),
    ),
    (
        PremadeListId::Sports,
        include_str!("../resources/premade-lists/sports.txt"),
    ),
    (
        PremadeListId::Forums,
        include_str!("../resources/premade-lists/forums.txt"),
    ),
    (
        PremadeListId::Webemail,
        include_str!("../resources/premade-lists/webemail.txt"),
    ),
    (
        PremadeListId::Blog,
        include_str!("../resources/premade-lists/blog.txt"),
    ),
    (
        PremadeListId::Streaming,
        include_str!("../resources/premade-lists/streaming.txt"),
    ),
];

fn parse(txt: &str) -> HashSet<String> {
    txt.lines()
        .map(|l| l.trim().to_ascii_lowercase())
        .filter(|l| !l.is_empty())
        .collect()
}

static PARSED: OnceLock<HashMap<PremadeListId, HashSet<String>>> = OnceLock::new();

fn parsed() -> &'static HashMap<PremadeListId, HashSet<String>> {
    PARSED.get_or_init(|| LISTS.iter().map(|(id, txt)| (*id, parse(txt))).collect())
}

/// The domain set for one premade list, parsed once and cached.
pub fn domains(id: PremadeListId) -> &'static HashSet<String> {
    parsed()
        .get(&id)
        .unwrap_or_else(|| unreachable!("every PremadeListId variant has an entry in LISTS"))
}

/// Does `host` match an entry in `id`'s domain set? Exact host match, or `host` stripped of a
/// single leading `www.` — see the module doc for why this is not subdomain-wildcard matching.
fn list_matches(id: PremadeListId, host: &str) -> bool {
    let set = domains(id);
    if set.contains(host) {
        return true;
    }
    if let Some(stripped) = host.strip_prefix("www.") {
        return set.contains(stripped);
    }
    false
}

/// Is `host` blocked by any of the enabled premade lists?
pub fn is_blocked_by_premade(enabled: &[PremadeListId], host: &str) -> bool {
    let host = host.trim_end_matches('.').to_ascii_lowercase();
    enabled.iter().any(|id| list_matches(*id, &host))
}

/// All domains (bare + `www.` variant) across the enabled lists, for backends that must
/// materialize a static sinkhole config (dnsmasq, the macOS `/etc/hosts` splice).
pub fn expand_enabled(enabled: &[PremadeListId]) -> impl Iterator<Item = String> + '_ {
    enabled.iter().flat_map(|id| {
        domains(*id)
            .iter()
            .flat_map(|d| [d.clone(), format!("www.{d}")])
    })
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn shopping_list_blocks_amazon_but_not_the_aws_console() {
        assert!(list_matches(PremadeListId::Shopping, "amazon.com"));
        assert!(list_matches(PremadeListId::Shopping, "www.amazon.com"));
        assert!(!list_matches(PremadeListId::Shopping, "aws.amazon.com"));
        assert!(!list_matches(PremadeListId::Shopping, "console.aws.amazon.com"));
        assert!(!list_matches(PremadeListId::Shopping, "signin.aws.amazon.com"));
    }

    #[test]
    fn is_blocked_by_premade_checks_every_enabled_list() {
        assert!(is_blocked_by_premade(
            &[PremadeListId::Social],
            "www.reddit.com"
        ));
        assert!(!is_blocked_by_premade(&[], "www.reddit.com"));
    }

    #[test]
    fn a_newly_added_category_is_blocked_only_when_enabled() {
        let sample = domains(PremadeListId::Gambling)
            .iter()
            .next()
            .cloned()
            .expect("gambling list should be non-empty");
        assert!(is_blocked_by_premade(&[PremadeListId::Gambling], &sample));
        assert!(!is_blocked_by_premade(&[PremadeListId::Social], &sample));
    }

    #[test]
    fn expand_enabled_includes_bare_and_www_variants() {
        let expanded: HashSet<String> = expand_enabled(&[PremadeListId::Social]).collect();
        assert!(expanded.contains("reddit.com"));
        assert!(expanded.contains("www.reddit.com"));
    }
}
