//! Built-in bulk domain blocklists (nsfw, shopping, social, gambling, press, games, sports,
//! forums, webemail, blog, streaming), embedded at compile time so every packaging path
//! (electron-builder on Windows/macOS, the Linux .deb, and the NixOS flake that builds this
//! crate from source) ships them with zero extra staging steps. The source `.txt` files are
//! regenerated by `scripts/update-blocklists.mjs`, which normalizes every upstream source down
//! to registrable (eTLD+1) domains before writing them here.
//!
//! Browser DNR domain conditions match a domain and its subdomains. Native matching deliberately
//! uses the same rule, including the generated per-category exemptions for shared services.

use std::collections::HashSet;
use std::sync::OnceLock;

use crate::policy::{
    premade_list_exemptions, premade_list_source, PremadeListId, PREMADE_LIST_COUNT,
};

fn parse(txt: &'static str) -> HashSet<&'static str> {
    txt.lines()
        .map(str::trim)
        .filter(|line| !line.is_empty())
        .collect()
}

// Each category is parsed only if it is actually enabled. Borrowing from include_str! avoids one
// heap allocation per domain while retaining constant-time membership checks.
static PARSED: [OnceLock<HashSet<&'static str>>; PREMADE_LIST_COUNT] =
    [const { OnceLock::new() }; PREMADE_LIST_COUNT];

/// The domain set for one premade list, parsed once and cached.
pub fn domains(id: PremadeListId) -> &'static HashSet<&'static str> {
    PARSED[id.as_index()].get_or_init(|| parse(premade_list_source(id)))
}

fn is_exempt(id: PremadeListId, host: &str) -> bool {
    premade_list_exemptions(id).iter().any(|domain| {
        host == *domain
            || host
                .strip_suffix(domain)
                .is_some_and(|prefix| prefix.ends_with('.'))
    })
}

/// Does `host` match a domain or subdomain in `id`, unless a generated exemption covers it?
fn list_matches(id: PremadeListId, host: &str) -> bool {
    if is_exempt(id, host) {
        return false;
    }
    let set = domains(id);
    let mut candidate = host;
    loop {
        if set.contains(candidate) {
            return true;
        }
        let Some((_, parent)) = candidate.split_once('.') else {
            return false;
        };
        candidate = parent;
    }
}

/// Is `host` blocked by any of the enabled premade lists?
pub fn is_blocked_by_premade(enabled: &[PremadeListId], host: &str) -> bool {
    let host = host.trim_end_matches('.').to_ascii_lowercase();
    enabled.iter().any(|id| list_matches(*id, &host))
}

/// All domains across enabled lists for backends that materialize a DNS sinkhole. dnsmasq applies
/// them to subdomains; hosts-file enforcement additionally writes the common `www.` name.
pub fn expand_enabled(enabled: &[PremadeListId]) -> impl Iterator<Item = String> + '_ {
    enabled.iter().flat_map(|id| {
        domains(*id)
            .iter()
            .filter(move |domain| !is_exempt(*id, domain))
            .map(|domain| (*domain).to_owned())
    })
}

/// Generated subdomain exceptions for DNS backends whose parent-domain rules need explicit
/// longest-match routes back to the normal resolver.
pub fn expand_exemptions(enabled: &[PremadeListId]) -> impl Iterator<Item = &'static str> + '_ {
    enabled
        .iter()
        .flat_map(|id| premade_list_exemptions(*id).iter().copied())
        // An exception belongs to one category, not to the whole policy. If another enabled
        // category blocks that hostname, emitting a global dnsmasq `server=/.../#` route would
        // incorrectly override the other category's sinkhole rule.
        .filter(move |domain| !enabled.iter().any(|id| list_matches(*id, domain)))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn shopping_list_blocks_amazon_but_not_the_aws_console() {
        assert!(list_matches(PremadeListId::Shopping, "amazon.com"));
        assert!(list_matches(PremadeListId::Shopping, "www.amazon.com"));
        assert!(!list_matches(PremadeListId::Shopping, "aws.amazon.com"));
        assert!(!list_matches(
            PremadeListId::Shopping,
            "console.aws.amazon.com"
        ));
        assert!(!list_matches(
            PremadeListId::Shopping,
            "signin.aws.amazon.com"
        ));
    }

    #[test]
    fn one_lists_exemption_does_not_override_another_enabled_list() {
        let enabled = [PremadeListId::Shopping, PremadeListId::Streaming];
        assert!(is_blocked_by_premade(&enabled, "aws.amazon.com"));
        assert!(!expand_exemptions(&enabled).any(|domain| domain == "aws.amazon.com"));
    }

    #[test]
    fn is_blocked_by_premade_checks_every_enabled_list() {
        assert!(is_blocked_by_premade(
            &[PremadeListId::Social],
            "www.reddit.com"
        ));
        assert!(!is_blocked_by_premade(&[], "www.reddit.com"));
    }

    #[test]
    fn a_newly_added_category_is_blocked_only_when_enabled() {
        let sample = domains(PremadeListId::Gambling)
            .iter()
            .next()
            .cloned()
            .expect("gambling list should be non-empty");
        assert!(is_blocked_by_premade(&[PremadeListId::Gambling], &sample));
        assert!(!is_blocked_by_premade(&[PremadeListId::Social], &sample));
    }

    #[test]
    fn expand_enabled_includes_source_domains() {
        let expanded: HashSet<String> = expand_enabled(&[PremadeListId::Social]).collect();
        assert!(expanded.contains("reddit.com"));
    }
}
