[package]
name = "talysman-linux"
version = "0.6.0"
edition = "2021"
description = "Talysman privileged Linux service and installer."
publish = false

[lib]
name = "talysman"
path = "src/lib.rs"

[[bin]]
name = "talysman-svc"
path = "src/main.rs"

[[bin]]
name = "talysman-svcctl"
path = "src/bin/svcctl.rs"

[[bin]]
name = "talysman-natmsg"
path = "src/bin/natmsg.rs"

[[bin]]
name = "focus-enable"
path = "src/bin/focus-enable.rs"

[[bin]]
name = "focus-disable"
path = "src/bin/focus-disable.rs"

[[bin]]
name = "focus-toggle"
path = "src/bin/focus-toggle.rs"

[[bin]]
name = "talysman-tray"
path = "src/bin/tray.rs"

[dependencies]
anyhow = "1"
chrono = { version = "0.4", default-features = false, features = ["clock"] }
talysman_common = { path = "../common" }
rand = "0.8"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
sysinfo = "0.30"
tokio = { version = "1", features = ["rt-multi-thread", "net", "time", "sync", "io-util", "io-std", "macros", "signal"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
ksni = { version = "0.3", default-features = false, features = ["tokio"] }
image = { version = "0.25", default-features = false, features = ["png"] }

[profile.release]
opt-level = 3
lto = "thin"
codegen-units = 1
panic = "abort"
strip = true
