import { defineSite } from '../types.js';

export default defineSite({
  id: 'bluesky',
  label: 'Bluesky',
  hosts: ['bsky.app'],
  appHosts: ['bsky.app'],
  networkDomains: ['bsky.network', 'bsky.social'],
  features: [
    { id: 'content', label: 'Posts you open directly', description: 'A specific post and its replies.', default: 'allow' },
    { id: 'search', label: 'Search', default: 'allow' },
    { id: 'messages', label: 'Chat', default: 'allow' },
    { id: 'notifications', label: 'Notifications', default: 'allow' },
    { id: 'compose', label: 'Posting', default: 'allow' },
    { id: 'feed', label: 'Discover, Following & custom feeds', description: 'The feeds themselves, plus hashtag pages.', default: 'block' },
    { id: 'recommendations', label: 'Explore, trending & suggested follows', default: 'block' },
    { id: 'profiles', label: 'Profiles', default: 'block' },
    { id: 'essentials', label: 'Sign-in & settings', default: 'allow', locked: true },
  ],
  routes: [
    { feature: 'content', path: '^/profile/[^/]+/post/([a-z0-9]+)(?:/.*)?$', judge: { contentSelector: 'main, [role="main"]' } },
    { feature: 'search', path: '^/search$', query: { q: '^[^&#]+$' } },
    { feature: 'recommendations', path: '^/(?:search|explore)$' },
    { feature: 'messages', path: '^/messages(?:/.*)?$' },
    { feature: 'notifications', path: '^/notifications(?:/.*)?$' },
    { feature: 'compose', path: '^/intent/compose$' },
    { feature: 'essentials', path: '^/(?:settings|moderation)(?:/.*)?$' },
    { feature: 'feed', path: '^/(?:feeds|lists|hashtag/[^/]+|profile/[^/]+/(?:feed|lists)/[^/]+)$' },
    { feature: 'profiles', path: '^/profile/[^/]+(?:/[a-z-]+)?$' },
  ],
  fallbackFeature: 'feed',
  elements: [
    { feature: 'feed', selector: 'main, [role="main"]', on: ['feed'] },
    // The right column's trending topics and suggested follows.
    { feature: 'recommendations', selector: '[data-testid*="trending" i], [data-testid*="suggested" i]' },
    { feature: 'recommendations', selector: 'main, [role="main"]', on: ['recommendations'] },
    { feature: 'content', selector: 'main, [role="main"]', on: ['content'] },
    { feature: 'search', selector: 'main, [role="main"]', on: ['search'] },
    { feature: 'messages', selector: 'main, [role="main"]', on: ['messages'] },
    { feature: 'notifications', selector: 'main, [role="main"]', on: ['notifications'] },
    { feature: 'compose', selector: '[role="dialog"]', on: ['compose'] },
    { feature: 'profiles', selector: 'main, [role="main"]', on: ['profiles'] },
  ],
  examples: [
    ['https://bsky.app/', 'feed'],
    ['https://bsky.app/feeds', 'feed'],
    ['https://bsky.app/hashtag/rust', 'feed'],
    ['https://bsky.app/profile/bsky.app/feed/whats-hot', 'feed'],
    ['https://bsky.app/profile/ada.bsky.social/post/3kabc123xyz', 'content'],
    ['https://bsky.app/profile/ada.bsky.social/post/3kabc123xyz/liked-by', 'content'],
    ['https://bsky.app/search?q=rust', 'search'],
    ['https://bsky.app/search', 'recommendations'],
    ['https://bsky.app/messages/abc', 'messages'],
    ['https://bsky.app/notifications', 'notifications'],
    ['https://bsky.app/intent/compose?text=hi', 'compose'],
    ['https://bsky.app/settings/account', 'essentials'],
    ['https://bsky.app/profile/ada.bsky.social', 'profiles'],
    ['https://bsky.app/profile/ada.bsky.social/followers', 'profiles'],
    ['https://docs.bsky.app/', 'feed'],
  ],
  captureSeeds: [
    'https://bsky.app/',
    'https://bsky.app/search?q=news',
    'https://bsky.app/search',
    'https://bsky.app/notifications',
    'https://bsky.app/messages',
    'https://bsky.app/feeds',
    'https://bsky.app/hashtag/news',
    'https://bsky.app/profile/bsky.app/feed/whats-hot',
    'https://bsky.app/intent/compose?text=hi',
    'https://bsky.app/profile/bsky.app',
  ],
  android: { packages: ['xyz.blueskyweb.app'] },
});
