import { defineSite } from '../types.js';

export default defineSite({
  id: 'facebook',
  label: 'Facebook',
  hosts: ['facebook.com', 'fb.watch'],
  appHosts: ['facebook.com', 'www.facebook.com', 'm.facebook.com', 'web.facebook.com', 'mbasic.facebook.com', 'fb.watch'],
  networkDomains: ['fbcdn.net', 'facebook.net', 'fbsbx.com'],
  features: [
    { id: 'content', label: 'Posts & photos you open directly', default: 'allow' },
    { id: 'search', label: 'Search', default: 'allow' },
    { id: 'messages', label: 'Messages', default: 'allow' },
    { id: 'notifications', label: 'Notifications', default: 'allow' },
    { id: 'groups', label: 'Groups', default: 'allow' },
    { id: 'marketplace', label: 'Marketplace', default: 'allow' },
    { id: 'events', label: 'Events', default: 'allow' },
    { id: 'feed', label: 'News feed', description: 'Posts on the home page. The page itself stays usable for posting.', default: 'block' },
    {
      id: 'reels',
      label: 'Reels & video',
      description: 'The Reels and Video tabs, and every reel or video, including ones you open from a link.',
      default: 'block',
    },
    { id: 'stories', label: 'Stories', default: 'block' },
    { id: 'recommendations', label: 'Suggestions & sponsored', description: 'The right rail and People You May Know.', default: 'block' },
    { id: 'profiles', label: 'Profiles & pages', default: 'block' },
    { id: 'essentials', label: 'Sign-in & settings', default: 'allow', locked: true },
  ],
  routes: [
    // The Reels and Video tabs redirect straight into a specific reel (/reel/<id>), so a reel or
    // video you open from a link can't be told apart from scrolling the tab: both are `reels`.
    { feature: 'reels', host: 'fb.watch' },
    { feature: 'content', path: '^/groups/[^/]+/(?:posts|permalink)/([0-9]+)(?:/.*)?$', judge: { contentSelector: '[role="main"]' } },
    { feature: 'content', path: '^/(?:[^/]+/)?(?:posts|videos|photos)/([^/]+)(?:/.*)?$', judge: { contentSelector: '[role="main"]' } },
    { feature: 'content', path: '^/share/p/([-_a-z0-9]+)$' },
    { feature: 'content', path: '^/(?:permalink|story)\\.php$', query: { story_fbid: '^[^&#]+$' } },
    { feature: 'content', path: '^/photo(?:\\.php)?$', query: { fbid: '^[0-9]+$' } },
    { feature: 'search', path: '^/search(?:/[^/]+)?$', query: { q: '^[^&#]+$' } },
    { feature: 'messages', path: '^/messages(?:/.*)?$' },
    { feature: 'notifications', path: '^/notifications$' },
    { feature: 'groups', path: '^/groups(?:/.*)?$' },
    { feature: 'marketplace', path: '^/marketplace(?:/.*)?$' },
    { feature: 'events', path: '^/events(?:/.*)?$' },
    { feature: 'reels', path: '^/(?:reels?|watch|share/[rv])(?:/.*)?$' },
    { feature: 'stories', path: '^/stories(?:/.*)?$' },
    { feature: 'recommendations', path: '^/friends/suggestions(?:/.*)?$' },
    {
      feature: 'essentials',
      path: '^/(?:login|login\\.php|logout\\.php|checkpoint|recover|r\\.php|reg|settings|privacy|security|help|two_step_verification|dialog|v[0-9.]+/dialog)(?:/.*)?$',
    },
    { feature: 'feed', path: '^/(?:home\\.php|search(?:/[^/]+)?)$' },
    { feature: 'profiles', path: '^/(?:profile\\.php|people/[^/]+/[0-9]+|[.a-z0-9]+)(?:/(?:about|friends|photos|videos|reels|followers|following)[_a-z]*)?$' },
  ],
  fallbackFeature: 'feed',
  elements: [
    // Facebook's class names are generated per build and its labels are translated, so these
    // anchor on ARIA roles/attributes and hrefs. Verified against captures (`pnpm check:sites`).
    // Each feed post is an `[aria-posinset]` item; loading placeholders are bare articles.
    { feature: 'feed', selector: '[role="main"] [aria-posinset], [role="main"] [role="article"]', on: ['feed'] },
    // The Reels tab (top bar) and the Reels/Video shortcuts (left rail).
    { feature: 'reels', selector: '[role="navigation"] a[href*="/reel"], [role="navigation"] a[href*="/watch"]' },
    { feature: 'reels', selector: '[role="main"]', on: ['reels'] },
    { feature: 'stories', selector: '[role="main"] [role="region"]:has(a[href*="/stories/"])' },
    { feature: 'stories', selector: '[role="main"]', on: ['stories'] },
    // The home page's right rail: sponsored posts and birthdays (chat contacts aren't in it).
    { feature: 'recommendations', selector: '#right_rail_container, [role="complementary"]', on: ['feed'] },
    { feature: 'recommendations', selector: '[role="main"]', on: ['recommendations'] },
    { feature: 'content', selector: '[role="main"]', on: ['content'] },
    { feature: 'search', selector: '[role="main"]', on: ['search'] },
    { feature: 'messages', selector: '[role="main"]', on: ['messages'] },
    { feature: 'notifications', selector: '[role="main"]', on: ['notifications'] },
    { feature: 'groups', selector: '[role="main"]', on: ['groups'] },
    { feature: 'marketplace', selector: '[role="main"]', on: ['marketplace'] },
    { feature: 'events', selector: '[role="main"]', on: ['events'] },
    { feature: 'profiles', selector: '[role="main"]', on: ['profiles'] },
  ],
  // Test-only anchors, checked against en-US captures, so labels are fine here.
  keep: [
    { name: 'search box', selector: '[role="banner"] input[type="search"]', feature: 'search' },
    { name: 'post composer', selector: '[role="main"] [role="region"][aria-label="Create a post"]', on: ['feed'] },
    { name: 'Messenger & notifications buttons', selector: '[role="banner"] [role="navigation"][aria-label="Account controls and settings"]' },
    { name: 'Groups & Marketplace tabs', selector: '[role="banner"] a[href^="/groups"], [role="banner"] a[href^="/marketplace"]' },
  ],
  examples: [
    ['https://www.facebook.com/', 'feed'],
    ['https://www.facebook.com/home.php', 'feed'],
    ['https://www.facebook.com/ada/posts/pfbid0abc123', 'content'],
    ['https://www.facebook.com/ada/videos/123456/', 'content'],
    ['https://www.facebook.com/groups/rustlang/posts/123456/', 'content'],
    ['https://www.facebook.com/groups/rustlang/permalink/123456/', 'content'],
    ['https://www.facebook.com/permalink.php?story_fbid=pfbid0abc&id=4', 'content'],
    ['https://www.facebook.com/photo/?fbid=123456', 'content'],
    ['https://www.facebook.com/watch/?v=123456', 'reels'],
    ['https://www.facebook.com/reel/123456', 'reels'],
    ['https://www.facebook.com/reel/?s=tab', 'reels'],
    ['https://www.facebook.com/share/p/AbC123/', 'content'],
    ['https://www.facebook.com/share/r/AbC123/', 'reels'],
    ['https://fb.watch/abc123/', 'reels'],
    ['https://www.facebook.com/search/top/?q=rust', 'search'],
    ['https://www.facebook.com/search/top/', 'feed'],
    ['https://www.facebook.com/messages/t/123', 'messages'],
    ['https://www.facebook.com/notifications', 'notifications'],
    ['https://www.facebook.com/groups/feed/', 'groups'],
    ['https://www.facebook.com/marketplace/nyc/', 'marketplace'],
    ['https://www.facebook.com/events/123456/', 'events'],
    ['https://www.facebook.com/watch/', 'reels'],
    ['https://www.facebook.com/reel/', 'reels'],
    ['https://www.facebook.com/stories/123/abc/', 'stories'],
    ['https://www.facebook.com/friends/suggestions', 'recommendations'],
    ['https://www.facebook.com/login/', 'essentials'],
    ['https://www.facebook.com/settings/?tab=account', 'essentials'],
    ['https://www.facebook.com/v19.0/dialog/oauth', 'essentials'],
    ['https://www.facebook.com/ada.lovelace', 'profiles'],
    ['https://www.facebook.com/ada.lovelace/about', 'profiles'],
    ['https://www.facebook.com/profile.php?id=123', 'profiles'],
    ['https://m.facebook.com/', 'feed'],
    ['https://developers.facebook.com/docs/', 'feed'],
  ],
  captureSeeds: [
    'https://www.facebook.com/',
    'https://www.facebook.com/search/top/?q=news',
    'https://www.facebook.com/watch/',
    'https://www.facebook.com/notifications',
    'https://www.facebook.com/messages/',
    'https://www.facebook.com/groups/feed/',
    'https://www.facebook.com/marketplace/',
    'https://www.facebook.com/events/',
    'https://www.facebook.com/friends/suggestions',
    'https://www.facebook.com/zuck',
  ],
  android: {
    packages: ['com.facebook.katana'],
    screens: [
      {
        feature: 'reels',
        match: [{ contentDesc: '^(Reels|Video)(, tab \\d+ of \\d+)?$', selected: true }],
        action: 'clickAlternative',
        alternative: { contentDesc: '^(Groups|Marketplace)(, tab \\d+ of \\d+)?$' },
        maxTested: '480.x',
      },
      {
        feature: 'feed',
        match: [{ contentDesc: '^Home(, tab \\d+ of \\d+)?$', selected: true }],
        action: 'overlay',
        maxTested: '480.x',
      },
    ],
  },
});
