import { defineSite } from '../types.js';

export default defineSite({
  id: 'instagram',
  label: 'Instagram',
  hosts: ['instagram.com'],
  appHosts: ['instagram.com', 'www.instagram.com'],
  networkDomains: ['cdninstagram.com', 'fbcdn.net'],
  features: [
    { id: 'content', label: 'Posts & reels you open directly', default: 'allow' },
    { id: 'search', label: 'Search', default: 'allow' },
    { id: 'messages', label: 'Direct messages', default: 'allow' },
    { id: 'compose', label: 'Posting', default: 'allow' },
    { id: 'feed', label: 'Home feed', description: 'Posts on the home page. The page itself stays usable for posting and notifications.', default: 'block' },
    { id: 'explore', label: 'Explore & Reels tab', default: 'block' },
    { id: 'stories', label: 'Stories', default: 'block' },
    { id: 'recommendations', label: 'Suggestions & swiping', description: 'Jumping from one post or reel to another.', default: 'block' },
    { id: 'profiles', label: 'Profiles', default: 'block' },
    { id: 'essentials', label: 'Sign-in & settings', default: 'allow', locked: true },
  ],
  routes: [
    { feature: 'content', path: '^/(?:[^/]+/)?(?:p|reel|reels|tv)/([-_a-z0-9]+)$', item: 1, judge: { contentSelector: 'article, main' } },
    { feature: 'search', path: '^/explore/search$', query: { q: '^[^&#]+$' } },
    { feature: 'messages', path: '^/direct(?:/.*)?$' },
    { feature: 'compose', path: '^/create(?:/.*)?$' },
    { feature: 'feed', path: '^/$', shell: true },
    { feature: 'explore', path: '^/(?:explore|reels)(?:/.*)?$' },
    { feature: 'stories', path: '^/stories(?:/.*)?$' },
    { feature: 'essentials', path: '^/(?:accounts|challenge|emails|session)(?:/.*)?$' },
    { feature: 'profiles', path: '^/[-_.a-z0-9]+(?:/(?:tagged|reels|saved))?$' },
  ],
  fallbackFeature: 'feed',
  hops: { feature: 'recommendations' },
  elements: [
    { feature: 'feed', selector: 'main', on: ['feed'] },
  ],
  entryPoints: [
    { feature: 'search', label: 'Search Instagram', url: 'https://www.instagram.com/explore/search/', param: 'q' },
    { feature: 'compose', label: 'Create or notifications', url: 'https://www.instagram.com/' },
    { feature: 'messages', label: 'Messages', url: 'https://www.instagram.com/direct/inbox/' },
  ],
  examples: [
    ['https://www.instagram.com/', 'feed'],
    ['https://www.instagram.com/explore/', 'explore'],
    ['https://www.instagram.com/reels/', 'explore'],
    ['https://www.instagram.com/p/ABC123/', 'content'],
    ['https://www.instagram.com/reel/ABC123/', 'content'],
    ['https://www.instagram.com/explore/search/?q=rust', 'search'],
    ['https://www.instagram.com/direct/inbox/', 'messages'],
    ['https://www.instagram.com/create/select/', 'compose'],
    ['https://www.instagram.com/stories/ada/123/', 'stories'],
    ['https://www.instagram.com/accounts/login/', 'essentials'],
    ['https://www.instagram.com/ada/', 'profiles'],
  ],
});
