import { defineSite } from '../types.js';

export default defineSite({
  id: 'linkedin',
  label: 'LinkedIn',
  hosts: ['linkedin.com'],
  appHosts: ['linkedin.com', 'www.linkedin.com', 'm.linkedin.com'],
  networkDomains: ['licdn.com'],
  features: [
    { id: 'content', label: 'Posts & articles you open directly', default: 'allow' },
    { id: 'search', label: 'Search', default: 'allow' },
    { id: 'messages', label: 'Messaging', default: 'allow' },
    { id: 'notifications', label: 'Notifications', default: 'allow' },
    { id: 'compose', label: 'Posting', default: 'allow' },
    { id: 'feed', label: 'Feed', description: 'Posts on the home page. The page itself stays usable for posting.', default: 'block' },
    { id: 'recommendations', label: 'Recommendations', description: 'The right rail and jumping from one post to another.', default: 'block' },
    { id: 'profiles', label: 'Profiles', default: 'block' },
    { id: 'jobs', label: 'Jobs', default: 'block' },
    { id: 'essentials', label: 'Sign-in & settings', default: 'allow', locked: true },
  ],
  routes: [
    { feature: 'content', path: '^/feed/update/urn:li:(?:activity|share|ugcpost):([0-9]+)(?:/.*)?$', item: 1, judge: { contentSelector: '.feed-shared-update-v2' } },
    { feature: 'content', path: '^/(?:posts|pulse)/([^/]+)$', item: 1, judge: { contentSelector: 'article, main' } },
    { feature: 'search', path: '^/search/results/[^/]+$', query: { keywords: '^[^&#]+$' } },
    { feature: 'messages', path: '^/messaging(?:/.*)?$' },
    { feature: 'notifications', path: '^/notifications(?:/.*)?$' },
    { feature: 'compose', path: '^/(?:post/new|content-management)(?:/.*)?$' },
    { feature: 'feed', path: '^/feed$', shell: true },
    { feature: 'profiles', path: '^/(?:in|company|school)/[^/]+(?:/.*)?$' },
    { feature: 'jobs', path: '^/jobs(?:/.*)?$' },
    { feature: 'essentials', path: '^/(?:login|signup|checkpoint|uas|authwall|psettings|mypreferences)(?:/.*)?$' },
  ],
  fallbackFeature: 'feed',
  hops: { feature: 'recommendations' },
  elements: [
    { feature: 'recommendations', selector: '.scaffold-layout__aside, .right-rail' },
    { feature: 'feed', selector: '.feed-shared-update-v2, [data-urn^="urn:li:activity:"], [data-urn^="urn:li:share:"]', on: ['feed'] },
  ],
  entryPoints: [
    { feature: 'search', label: 'Search LinkedIn posts', url: 'https://www.linkedin.com/search/results/content/', param: 'keywords' },
    { feature: 'compose', label: 'Post', url: 'https://www.linkedin.com/feed/' },
    { feature: 'notifications', label: 'Notifications', url: 'https://www.linkedin.com/notifications/' },
    { feature: 'messages', label: 'Messages', url: 'https://www.linkedin.com/messaging/' },
  ],
  examples: [
    ['https://www.linkedin.com/feed/', 'feed'],
    ['https://www.linkedin.com/feed/following/', 'feed'],
    ['https://www.linkedin.com/feed/update/urn:li:activity:123/', 'content'],
    ['https://www.linkedin.com/posts/ada_some-post-activity-123', 'content'],
    ['https://www.linkedin.com/pulse/some-article', 'content'],
    ['https://www.linkedin.com/search/results/content/?keywords=rust', 'search'],
    ['https://www.linkedin.com/search/results/content/', 'feed'],
    ['https://www.linkedin.com/messaging/', 'messages'],
    ['https://www.linkedin.com/notifications/', 'notifications'],
    ['https://www.linkedin.com/post/new/', 'compose'],
    ['https://www.linkedin.com/in/ada/', 'profiles'],
    ['https://www.linkedin.com/jobs/', 'jobs'],
    ['https://www.linkedin.com/login', 'essentials'],
    ['https://www.linkedin.com/mynetwork/', 'feed'],
  ],
});
