import { defineSite } from '../types.js';

export default defineSite({
  id: 'reddit',
  label: 'Reddit',
  hosts: ['reddit.com', 'redd.it'],
  appHosts: ['reddit.com', 'www.reddit.com', 'old.reddit.com', 'new.reddit.com', 'np.reddit.com', 'sh.reddit.com', 'chat.reddit.com', 'redd.it'],
  networkDomains: ['redditstatic.com', 'redditmedia.com'],
  features: [
    { id: 'content', label: 'Posts you open directly', description: 'A specific post and its discussion.', default: 'allow' },
    { id: 'comments', label: 'Comments', description: 'The discussion under a post.', default: 'allow' },
    { id: 'search', label: 'Search', default: 'allow' },
    { id: 'messages', label: 'Messages & chat', default: 'allow' },
    { id: 'notifications', label: 'Notifications', default: 'allow' },
    { id: 'compose', label: 'Posting', default: 'allow' },
    { id: 'feed', label: 'Feeds & subreddit listings', description: 'The posts on Home, Popular, All, and community front pages. The pages stay usable.', default: 'block' },
    { id: 'recommendations', label: 'Recommendations & related posts', description: 'Sidebars, trending, and more posts under the one you opened.', default: 'block' },
    { id: 'profiles', label: 'User profiles', default: 'block' },
    { id: 'essentials', label: 'Sign-in & settings', default: 'allow', locked: true },
  ],
  routes: [
    { feature: 'content', host: 'redd.it', path: '^/([a-z0-9]+)$' },
    { feature: 'messages', host: 'chat.reddit.com' },
    { feature: 'content', path: '^/(?:r/[^/]+/)?comments/([a-z0-9]+)(?:/.*)?$', judge: { contentSelector: 'shreddit-post' } },
    { feature: 'content', path: '^/gallery/([a-z0-9]+)$' },
    { feature: 'content', path: '^/r/[^/]+/s/([a-z0-9]+)$' },
    { feature: 'search', path: '^/(?:r/[^/]+/)?search$', query: { q: '^[^&#]+$' } },
    { feature: 'messages', path: '^/(?:message|chat)(?:/.*)?$' },
    { feature: 'notifications', path: '^/notifications$' },
    { feature: 'compose', path: '^/(?:r/[^/]+/)?submit$' },
    { feature: 'profiles', path: '^/(?:u|user)/[^/]+(?:/.*)?$' },
    { feature: 'essentials', path: '^/(?:login|register|password|account|settings|prefs)(?:/.*)?$' },
  ],
  fallbackFeature: 'feed',
  elements: [
    // New Reddit (shreddit) and old.reddit.com markup side by side.
    { feature: 'feed', selector: 'shreddit-feed, shreddit-gallery-carousel, #siteTable', on: ['feed'] },
    { feature: 'recommendations', selector: '[data-testid*="recommend"], [data-testid*="related"], [data-testid*="trending"], #right-sidebar-container, .trending-subreddits' },
    { feature: 'recommendations', selector: 'aside, shreddit-feed', on: ['content'] },
    { feature: 'comments', selector: 'shreddit-comment-tree, #comment-tree, .commentarea' },
    { feature: 'content', selector: 'main, .content[role="main"]', on: ['content'] },
    { feature: 'search', selector: 'main, .content[role="main"]', on: ['search'] },
    { feature: 'messages', selector: 'main, .content[role="main"]', on: ['messages'] },
    { feature: 'notifications', selector: 'main, .content[role="main"]', on: ['notifications'] },
    { feature: 'compose', selector: 'main, .content[role="main"]', on: ['compose'] },
    { feature: 'profiles', selector: 'main, .content[role="main"]', on: ['profiles'] },
  ],
  examples: [
    ['https://www.reddit.com/', 'feed'],
    ['https://www.reddit.com/r/rust/', 'feed'],
    ['https://www.reddit.com/r/popular', 'feed'],
    ['https://www.reddit.com/r/rust/comments/abc123/some_title/', 'content'],
    ['https://old.reddit.com/comments/abc123', 'content'],
    ['https://www.reddit.com/gallery/abc123', 'content'],
    ['https://www.reddit.com/r/rust/s/abc123', 'content'],
    ['https://redd.it/abc123', 'content'],
    ['https://redd.it/', 'feed'],
    ['https://www.reddit.com/search/?q=rust', 'search'],
    ['https://www.reddit.com/r/rust/search?q=async', 'search'],
    ['https://www.reddit.com/search/', 'feed'],
    ['https://www.reddit.com/message/inbox', 'messages'],
    ['https://chat.reddit.com/room/abc', 'messages'],
    ['https://www.reddit.com/notifications', 'notifications'],
    ['https://www.reddit.com/r/rust/submit', 'compose'],
    ['https://www.reddit.com/user/spez/', 'profiles'],
    ['https://www.reddit.com/login/', 'essentials'],
    ['https://ads.reddit.com/comments/abc123', 'feed'],
  ],
  android: { packages: ['com.reddit.frontpage'] },
});
