import { defineSite } from '../types.js';

export default defineSite({
  id: 'substack',
  label: 'Substack',
  hosts: ['substack.com'],
  // Every other subdomain is a publication (name.substack.com) and falls to `publications`.
  // Publications on custom domains aren't covered.
  appHosts: ['substack.com', 'www.substack.com'],
  networkDomains: ['substackcdn.com'],
  features: [
    { id: 'content', label: 'Posts & notes you open directly', default: 'allow' },
    { id: 'publications', label: 'Newsletter sites', description: 'A newsletter\'s own site (name.substack.com) and its posts.', default: 'allow' },
    { id: 'inbox', label: 'Subscriptions inbox', description: 'Posts from the newsletters you subscribe to.', default: 'allow' },
    { id: 'messages', label: 'Chat & messages', default: 'allow' },
    { id: 'notifications', label: 'Activity', default: 'allow' },
    { id: 'search', label: 'Search', default: 'allow' },
    { id: 'feed', label: 'Home, Notes & Explore', description: 'The algorithmic home feed, the Notes feed, and Explore and leaderboards.', default: 'block' },
    { id: 'recommendations', label: 'Recommendations', description: 'The sidebar of suggested people and newsletters, and a newsletter\'s recommended newsletters.', default: 'block' },
    { id: 'profiles', label: 'Profiles', default: 'block' },
    { id: 'essentials', label: 'Sign-in & account', default: 'allow', locked: true },
  ],
  routes: [
    // Email links go through /redirect and /app-link.
    { feature: 'essentials', path: '^/(?:sign-?in|sign-?up|account|settings|subscriptions|redirect|app-link|verify|logout|email-login|profile/edit)(?:/.*)?$' },
    { feature: 'content', path: '^/(?:@[^/]+/)?note/[cp]-[0-9]+$' },
    { feature: 'content', path: '^/@[^/]+/p-[0-9]+$' },
    { feature: 'content', path: '^/(?:home|inbox)/post/(?:p-)?[0-9]+$' },
    { feature: 'content', path: '^/pub/[^/]+/p/[^/]+$' },
    { feature: 'inbox', path: '^/inbox(?:/.*)?$' },
    { feature: 'messages', path: '^/(?:chat|messages)(?:/.*)?$' },
    { feature: 'notifications', path: '^/activity(?:/.*)?$' },
    { feature: 'search', path: '^/search(?:/.*)?$' },
    { feature: 'profiles', path: '^/(?:@[^/]+|profile/[^/]+)(?:/.*)?$' },
    // Everything else on substack.com: home, notes, explore, browse, top, leaderboards.
    { feature: 'feed' },
  ],
  fallbackFeature: 'publications',
  elements: [
    // `main.reader-nav-page` is the substack.com app's page column; the left nav sits outside it.
    { feature: 'feed', selector: 'main.reader-nav-page', on: ['feed'] },
    {
      feature: 'recommendations',
      selector: '.reader2-inbox-sidebar, [class*="exploreSidebar-"]',
      on: ['feed', 'content', 'inbox', 'notifications', 'search', 'profiles'],
    },
    { feature: 'recommendations', selector: '.homepage-recommendations, .homepage-recommendations-view-all', on: ['publications'] },
    { feature: 'content', selector: 'main.reader-nav-page', on: ['content'] },
    { feature: 'publications', selector: '#main', on: ['publications'] },
    { feature: 'inbox', selector: 'main.reader-nav-page', on: ['inbox'] },
    { feature: 'messages', selector: 'main.reader-nav-page', on: ['messages'] },
    { feature: 'notifications', selector: 'main.reader-nav-page', on: ['notifications'] },
    { feature: 'search', selector: 'main.reader-nav-page', on: ['search'] },
    { feature: 'profiles', selector: 'main.reader-nav-page', on: ['profiles'] },
  ],
  examples: [
    ['https://substack.com/', 'feed'],
    ['https://substack.com/home', 'feed'],
    ['https://substack.com/notes', 'feed'],
    ['https://substack.com/browse', 'feed'],
    ['https://substack.com/top/technology', 'feed'],
    ['https://substack.com/leaderboard/bestseller/rising', 'feed'],
    ['https://substack.com/note/c-326587767', 'content'],
    ['https://substack.com/@saribotton/note/c-343882223', 'content'],
    ['https://substack.com/@saribotton/p-123456', 'content'],
    ['https://substack.com/home/post/p-123456', 'content'],
    ['https://substack.com/inbox/post/123456', 'content'],
    ['https://substack.com/inbox', 'inbox'],
    ['https://substack.com/chat', 'messages'],
    ['https://substack.com/chat/123/post/abc', 'messages'],
    ['https://substack.com/activity', 'notifications'],
    ['https://substack.com/search/ai?searching=top', 'search'],
    ['https://substack.com/@saribotton', 'profiles'],
    ['https://substack.com/profile/123-sari-botton', 'profiles'],
    ['https://substack.com/sign-in', 'essentials'],
    ['https://substack.com/redirect/abc-123', 'essentials'],
    ['https://natesnewsletter.substack.com/', 'publications'],
    ['https://natesnewsletter.substack.com/p/every-ai-you-use-forgets-you-heres', 'publications'],
  ],
});
