import { defineSite } from '../types.js';

export default defineSite({
  id: 'tiktok',
  label: 'TikTok',
  hosts: ['tiktok.com'],
  appHosts: ['tiktok.com', 'www.tiktok.com', 'm.tiktok.com', 'vm.tiktok.com', 'vt.tiktok.com'],
  networkDomains: ['tiktokcdn.com', 'tiktokcdn-us.com', 'tiktokv.com', 'tiktokv.us', 'ttwstatic.com', 'byteoversea.com', 'ibytedtos.com', 'ibyteimg.com'],
  features: [
    { id: 'content', label: 'Videos you open directly', default: 'allow' },
    { id: 'search', label: 'Search', default: 'allow' },
    { id: 'messages', label: 'Messages', default: 'allow' },
    { id: 'compose', label: 'Uploading & TikTok Studio', default: 'allow' },
    { id: 'feed', label: 'For You, Following & Explore', description: 'The video feeds, LIVE, and hashtag and sound pages.', default: 'block' },
    { id: 'recommendations', label: 'Suggested videos & accounts', description: 'More videos beside the one you opened, and suggested accounts.', default: 'block' },
    { id: 'profiles', label: 'Profiles', default: 'block' },
    { id: 'essentials', label: 'Sign-in & settings', default: 'allow', locked: true },
  ],
  routes: [
    { feature: 'content', host: 'vm.tiktok.com', path: '^/([a-z0-9]+)$' },
    { feature: 'content', host: 'vt.tiktok.com', path: '^/([a-z0-9]+)$' },
    { feature: 'content', path: '^/@[^/]+/(?:video|photo)/([0-9]+)$', judge: { contentSelector: '[id^="main-content"], main' } },
    { feature: 'content', path: '^/(?:t|embed(?:/v2)?)/([a-z0-9]+)$' },
    { feature: 'search', path: '^/search(?:/(?:user|video|live|photo))?$', query: { q: '^[^&#]+$' } },
    { feature: 'messages', path: '^/messages$' },
    { feature: 'compose', path: '^/(?:upload|tiktokstudio|creator-center)(?:/.*)?$' },
    { feature: 'essentials', path: '^/(?:login|signup|logout|setting|legal|passport|feedback)(?:/.*)?$' },
    { feature: 'profiles', path: '^/@[^/]+$' },
  ],
  fallbackFeature: 'feed',
  elements: [
    // TikTok tags its markup with `data-e2e` attributes; every page's content sits in a
    // `#main-content-<page>` column beside the side nav.
    { feature: 'feed', selector: '[id^="main-content"], main', on: ['feed'] },
    { feature: 'recommendations', selector: '[data-e2e*="suggest"], [data-e2e*="recommend"], [data-e2e*="related"]' },
    { feature: 'content', selector: '[id^="main-content"], main', on: ['content'] },
    { feature: 'search', selector: '[id^="main-content"], main', on: ['search'] },
    { feature: 'messages', selector: '[id^="main-content"], main', on: ['messages'] },
    { feature: 'compose', selector: '[data-e2e="upload-icon"]' },
    { feature: 'compose', selector: '[id^="main-content"], main', on: ['compose'] },
    { feature: 'profiles', selector: '[id^="main-content"], main', on: ['profiles'] },
  ],
  examples: [
    ['https://www.tiktok.com/', 'feed'],
    ['https://www.tiktok.com/foryou', 'feed'],
    ['https://www.tiktok.com/following', 'feed'],
    ['https://www.tiktok.com/explore', 'feed'],
    ['https://www.tiktok.com/tag/rust', 'feed'],
    ['https://www.tiktok.com/@ada/video/7234567890123456789', 'content'],
    ['https://www.tiktok.com/@ada/photo/7234567890123456789', 'content'],
    ['https://www.tiktok.com/t/ZTabc123/', 'content'],
    ['https://vm.tiktok.com/ZMabc123/', 'content'],
    ['https://vm.tiktok.com/', 'feed'],
    ['https://www.tiktok.com/search?q=rust', 'search'],
    ['https://www.tiktok.com/search/user?q=rust', 'search'],
    ['https://www.tiktok.com/search', 'feed'],
    ['https://www.tiktok.com/messages', 'messages'],
    ['https://www.tiktok.com/tiktokstudio/upload', 'compose'],
    ['https://www.tiktok.com/login', 'essentials'],
    ['https://www.tiktok.com/setting', 'essentials'],
    ['https://www.tiktok.com/@ada', 'profiles'],
    ['https://www.tiktok.com/@ada/live', 'feed'],
    ['https://ads.tiktok.com/', 'feed'],
  ],
  captureSeeds: [
    'https://www.tiktok.com/',
    'https://www.tiktok.com/explore',
    'https://www.tiktok.com/search?q=cooking',
    'https://www.tiktok.com/messages',
    'https://www.tiktok.com/tiktokstudio/upload',
    'https://www.tiktok.com/@tiktok',
  ],
  android: { packages: ['com.zhiliaoapp.musically', 'com.ss.android.ugc.trill'] },
});
