import { defineSite } from '../types.js';

export default defineSite({
  id: 'x',
  label: 'X',
  hosts: ['x.com', 'twitter.com'],
  appHosts: ['x.com', 'www.x.com', 'mobile.x.com', 'twitter.com', 'www.twitter.com', 'mobile.twitter.com'],
  networkDomains: ['twimg.com'],
  features: [
    { id: 'content', label: 'Posts you open directly', description: 'A specific post and its replies.', default: 'allow' },
    { id: 'search', label: 'Search', default: 'allow' },
    { id: 'messages', label: 'Messages', default: 'allow' },
    { id: 'notifications', label: 'Notifications', default: 'allow' },
    { id: 'compose', label: 'Posting', default: 'allow' },
    { id: 'feed', label: 'Home timeline & Explore', default: 'block' },
    { id: 'recommendations', label: 'Trends & who to follow', description: 'The sidebar, suggested accounts, and jumping from one post to another.', default: 'block' },
    { id: 'profiles', label: 'Profiles', default: 'block' },
    { id: 'essentials', label: 'Sign-in & settings', default: 'allow', locked: true },
  ],
  routes: [
    { feature: 'content', path: '^/(?:i/)?(?:[^/]+/)?status/([0-9]+)(?:/.*)?$', item: 1, judge: { contentSelector: 'article[data-testid="tweet"]' } },
    { feature: 'search', path: '^/search$', query: { q: '^[^&#]+$' } },
    { feature: 'messages', path: '^/(?:messages|i/chat)(?:/.*)?$' },
    { feature: 'notifications', path: '^/(?:i/)?notifications(?:/.*)?$' },
    { feature: 'compose', path: '^/compose/post$' },
    { feature: 'essentials', path: '^/(?:i/flow/[^/]+|settings(?:/.*)?|login|logout)$' },
    { feature: 'feed', path: '^/(?:home|explore|search|i/.*)(?:/.*)?$' },
    { feature: 'profiles', path: '^/[a-z0-9_]{1,15}(?:/(?:with_replies|media|likes|highlights|articles|followers|following))?$' },
  ],
  fallbackFeature: 'feed',
  hops: { feature: 'recommendations' },
  elements: [
    { feature: 'recommendations', selector: '[data-testid="sidebarColumn"], [data-testid="trend"]' },
    { feature: 'recommendations', selector: '[data-testid="UserCell"]', on: ['content'] },
    { feature: 'feed', selector: '[data-testid="primaryColumn"] article', on: ['compose'] },
  ],
  entryPoints: [
    { feature: 'search', label: 'Search X', url: 'https://x.com/search', param: 'q' },
    { feature: 'compose', label: 'Post', url: 'https://x.com/compose/post' },
    { feature: 'notifications', label: 'Notifications', url: 'https://x.com/notifications' },
    { feature: 'messages', label: 'Messages', url: 'https://x.com/messages' },
  ],
  examples: [
    ['https://x.com/home', 'feed'],
    ['https://x.com/', 'feed'],
    ['https://x.com/explore/tabs/trending', 'feed'],
    ['https://x.com/ada/status/123', 'content'],
    ['https://x.com/ada/status/123/photo/1', 'content'],
    ['https://twitter.com/ada/status/123', 'content'],
    ['https://x.com/i/status/123', 'content'],
    ['https://x.com/search?q=rust', 'search'],
    ['https://x.com/search', 'feed'],
    ['https://x.com/messages', 'messages'],
    ['https://x.com/notifications', 'notifications'],
    ['https://x.com/compose/post', 'compose'],
    ['https://x.com/i/flow/login', 'essentials'],
    ['https://x.com/settings/account', 'essentials'],
    ['https://x.com/ada', 'profiles'],
    ['https://x.com/ada/media', 'profiles'],
    ['https://twitter.com/home', 'feed'],
    ['https://api.x.com/ada/status/123', 'feed'],
  ],
});
