import { defineSite } from '../types.js';

export default defineSite({
  id: 'x',
  label: 'X',
  hosts: ['x.com', 'twitter.com'],
  appHosts: ['x.com', 'www.x.com', 'mobile.x.com', 'twitter.com', 'www.twitter.com', 'mobile.twitter.com'],
  networkDomains: ['twimg.com'],
  features: [
    { id: 'content', label: 'Posts you open directly', description: 'A specific post and its replies.', default: 'allow' },
    { id: 'search', label: 'Search', default: 'allow' },
    { id: 'messages', label: 'Messages', default: 'allow' },
    { id: 'notifications', label: 'Notifications', default: 'allow' },
    { id: 'compose', label: 'Posting', default: 'allow' },
    { id: 'feed', label: 'Home timeline & Explore', description: 'The timelines themselves. Home and Explore stay usable for posting and search.', default: 'block' },
    { id: 'recommendations', label: 'Trends & who to follow', description: 'Trends, suggested accounts, and "Discover more" under a post.', default: 'block' },
    { id: 'profiles', label: 'Profiles', default: 'block' },
    { id: 'essentials', label: 'Sign-in & settings', default: 'allow', locked: true },
  ],
  routes: [
    { feature: 'content', path: '^/(?:i/)?(?:[^/]+/)?status/([0-9]+)(?:/.*)?$', judge: { contentSelector: 'article[data-testid="tweet"]' } },
    { feature: 'search', path: '^/search$', query: { q: '^[^&#]+$' } },
    { feature: 'messages', path: '^/(?:messages|i/chat)(?:/.*)?$' },
    { feature: 'notifications', path: '^/(?:i/)?notifications(?:/.*)?$' },
    { feature: 'compose', path: '^/compose/post$' },
    { feature: 'essentials', path: '^/(?:i/flow/[^/]+|settings(?:/.*)?|login|logout)$' },
    { feature: 'feed', path: '^/(?:home|explore|search|i/.*)(?:/.*)?$' },
    { feature: 'profiles', path: '^/[a-z0-9_]{1,15}(?:/(?:with_replies|media|likes|highlights|articles|followers|following))?$' },
  ],
  fallbackFeature: 'feed',
  elements: [
    // A timeline is a `section[role=region]` in the primary column; the composer, tab bar, and
    // search box sit outside it.
    { feature: 'feed', selector: '[data-testid="primaryColumn"] section[role="region"]', on: ['feed', 'compose'] },
    // The sidebar's search box isn't in a section/aside, so it stays.
    { feature: 'recommendations', selector: '[data-testid="sidebarColumn"] :is(section, aside), [data-testid="trend"]' },
    // Suggested accounts, and the "Discover more" block (a heading cell and everything after it).
    { feature: 'recommendations', selector: '[data-testid="UserCell"], [data-testid="cellInnerDiv"]:has(h2), [data-testid="cellInnerDiv"]:has(h2) ~ [data-testid="cellInnerDiv"]', on: ['content'] },
    { feature: 'content', selector: '[data-testid="primaryColumn"] section[role="region"]', on: ['content'] },
    { feature: 'search', selector: '[data-testid="primaryColumn"] section[role="region"]', on: ['search'] },
    { feature: 'profiles', selector: '[data-testid="primaryColumn"] section[role="region"]', on: ['profiles'] },
    { feature: 'notifications', selector: '[data-testid="primaryColumn"]', on: ['notifications'] },
    { feature: 'messages', selector: 'main[role="main"]', on: ['messages'] },
    { feature: 'compose', selector: '[data-testid="SideNav_NewTweet_Button"], [data-testid="tweetButtonInline"]' },
    { feature: 'compose', selector: '[role="dialog"]', on: ['compose'] },
  ],
  examples: [
    ['https://x.com/home', 'feed'],
    ['https://x.com/', 'feed'],
    ['https://x.com/explore/tabs/trending', 'feed'],
    ['https://x.com/ada/status/123', 'content'],
    ['https://x.com/ada/status/123/photo/1', 'content'],
    ['https://twitter.com/ada/status/123', 'content'],
    ['https://x.com/i/status/123', 'content'],
    ['https://x.com/search?q=rust', 'search'],
    ['https://x.com/search', 'feed'],
    ['https://x.com/messages', 'messages'],
    ['https://x.com/notifications', 'notifications'],
    ['https://x.com/compose/post', 'compose'],
    ['https://x.com/i/flow/login', 'essentials'],
    ['https://x.com/settings/account', 'essentials'],
    ['https://x.com/ada', 'profiles'],
    ['https://x.com/ada/media', 'profiles'],
    ['https://twitter.com/home', 'feed'],
    ['https://api.x.com/ada/status/123', 'feed'],
  ],
  android: { packages: ['com.twitter.android'] },
});
