import { defineSite } from '../types.js';

// The hiding features mirror Unhook (unhook.app, v1.6.9) one to one: same options, same defaults,
// same selectors (desktop and m.youtube.com). Unhook's scripted options (disable autoplay and
// annotations, the home/subscriptions/trending redirects, the title's notification count) aren't
// hiding and aren't mirrored. `content`, `search` and `studio` own pages for the AI judge.
export default defineSite({
  id: 'youtube',
  label: 'YouTube',
  hosts: ['youtube.com', 'youtu.be'],
  appHosts: ['youtube.com', 'www.youtube.com', 'm.youtube.com', 'studio.youtube.com', 'youtu.be'],
  networkDomains: ['ytimg.com', 'googlevideo.com', 'ggpht.com'],
  features: [
    { id: 'feed', label: 'Home feed', default: 'block' },
    { id: 'sidebar', label: 'Video sidebar', description: 'Everything beside the video: recommendations, live chat, and playlists.', default: 'block' },
    { id: 'recommendations', label: 'Recommended videos', description: 'Up next beside the video, and the suggestions shown when it is paused.', default: 'block' },
    { id: 'live_chat', label: 'Live chat', default: 'block' },
    { id: 'playlist', label: 'Playlist panel', default: 'block' },
    { id: 'fundraiser', label: 'Fundraisers', default: 'block' },
    { id: 'end_screen', label: 'End screen video wall', default: 'block' },
    { id: 'end_cards', label: 'End screen cards', default: 'block' },
    { id: 'shorts', label: 'Shorts', default: 'allow' },
    { id: 'comments', label: 'Comments', default: 'allow' },
    { id: 'profile_photos', label: 'Profile photos in comments', default: 'allow' },
    { id: 'mixes', label: 'Mixes', default: 'allow' },
    { id: 'merch', label: 'Merch, tickets & offers', default: 'block' },
    { id: 'video_info', label: 'Video info', description: 'Title, channel, buttons, and description under the video.', default: 'allow' },
    { id: 'buttons_bar', label: 'Like & share buttons', default: 'allow' },
    { id: 'channel_info', label: 'Channel & subscribe button', default: 'allow' },
    { id: 'description', label: 'Video description', default: 'allow' },
    { id: 'header', label: 'Top header', default: 'allow' },
    { id: 'notifications', label: 'Notification bell', default: 'block' },
    { id: 'inapt_search', label: 'Unrelated search results', description: '"People also watched", "Latest from", and other shelves mixed into search.', default: 'block' },
    { id: 'trending', label: 'Explore & trending', default: 'allow' },
    { id: 'more_from_youtube', label: 'More from YouTube', default: 'block' },
    { id: 'subscriptions', label: 'Subscriptions', default: 'allow' },
    { id: 'content', label: 'Videos you open directly', default: 'allow' },
    { id: 'search', label: 'Search', default: 'allow' },
    { id: 'studio', label: 'YouTube Studio & uploads', default: 'allow' },
    { id: 'essentials', label: 'Sign-in & account', default: 'allow', locked: true },
    // Unhook hides these unconditionally.
    { id: 'promos', label: 'Promos & surveys', default: 'block', locked: true },
  ],
  routes: [
    { feature: 'studio', host: 'studio.youtube.com' },
    { feature: 'content', host: 'youtu.be', path: '^/([-_a-z0-9]{11})$' },
    { feature: 'content', path: '^/watch$', query: { v: '^[-_a-zA-Z0-9]{11}$' }, judge: { contentSelector: 'ytd-watch-metadata, #above-the-fold' } },
    { feature: 'content', path: '^/live/([-_a-z0-9]{11})$' },
    { feature: 'shorts', path: '^/shorts/([-_a-z0-9]{11})$' },
    { feature: 'search', path: '^/results$', query: { search_query: '^[^&#]+$' } },
    { feature: 'studio', path: '^/upload$' },
    { feature: 'essentials', path: '^/(?:account(?:_[^/]+)?|signin|logout|premium|paid_memberships)(?:/.*)?$' },
  ],
  fallbackFeature: 'feed',
  elements: [
    {
      feature: 'feed',
      selector: 'ytd-browse[page-subtype=home] .ytd-rich-grid-renderer, ytd-browse[role=main]:not([page-subtype]):not(:has(#header #page-header-container)):has(ytd-feed-filter-chip-bar-renderer) .ytd-rich-grid-renderer, div[tab-identifier=FEwhat_to_watch]',
    },
    { feature: 'sidebar', selector: '#secondary.ytd-watch-flexy' },
    {
      feature: 'recommendations',
      selector: '#items.ytd-watch-next-secondary-results-renderer, .ytd-watch-grid > #contents, .ytp-pause-overlay, ytm-item-section-renderer[section-identifier=related-items]',
    },
    { feature: 'live_chat', selector: 'ytd-live-chat-frame#chat' },
    { feature: 'playlist', selector: '#playlist, ytm-playlist' },
    { feature: 'fundraiser', selector: '#donation-shelf, ytm-donation-shelf-renderer-outer' },
    {
      feature: 'end_screen',
      selector: '.html5-endscreen:not(.mweb-endscreen), .ytp-fullscreen-grid, .ytp-mweb-endscreen-play-next, .ytp-mweb-endscreen-play-previous',
    },
    { feature: 'end_cards', selector: '.ytp-ce-element, .ytp-ce-hide-button-container' },
    {
      feature: 'shorts',
      selector: '.yt-simple-endpoint[title=Shorts], #player-shorts-container, .ytd-shorts, yt-chip-cloud-chip-renderer:has(yt-formatted-string[title=Shorts]), yt-tab-shape[tab-title=Shorts], ytd-compact-video-renderer:has(a[href*="/shorts/"]), ytd-notification-renderer:has(> a[href^="/shorts/"]), ytd-reel-shelf-renderer, ytd-rich-grid-renderer[is-shorts-grid], ytd-rich-item-renderer:has(a[href*="/shorts/"]), ytd-rich-shelf-renderer[is-shorts], ytd-video-renderer:has(a[href*="/shorts/"]), ytm-reel-shelf-renderer, ytm-rich-grid-renderer.is_shorts, ytm-video-with-context-renderer:has(a[href*="/shorts/"]), ytm-pivot-bar-renderer > ytm-pivot-bar-item-renderer:has(.pivot-shorts)',
    },
    {
      feature: 'comments',
      selector: '#comment-teaser, #comments, ytm-comment-section-renderer, ytm-comments-entry-point-header-renderer, ytm-engagement-panel',
    },
    { feature: 'profile_photos', selector: '.ytd-comment-renderer yt-img-shadow, .comment-icon-container' },
    {
      feature: 'mixes',
      selector: '.ytp-videowall-still[data-is-mix=true], a[href*="start_radio=1"], ytd-browse[page-subtype=home] ytd-video-meta-block[radio-meta], ytd-compact-radio-renderer, ytd-radio-renderer, ytd-rich-item-renderer:has(a[href*="start_radio=1"]), ytm-compact-radio-renderer, ytm-radio-renderer',
    },
    {
      feature: 'merch',
      selector: '#clarify-box, #offer-module, #ticket-shelf, .ytp-drawer, yt-alert-with-actions-renderer, ytd-merch-shelf-renderer, ytd-metadata-row-container-renderer > #always-shown, ytm-compact-offer-module-renderer',
    },
    { feature: 'video_info', selector: '#primary-inner > #info, ytd-watch-metadata, ytm-item-section-renderer[section-identifier=slim-video-metadata]' },
    { feature: 'buttons_bar', selector: '#actions.ytd-watch-metadata, #info > #menu-container, .slim-video-metadata-actions' },
    { feature: 'channel_info', selector: '#owner.ytd-watch-metadata, #top-row.ytd-video-secondary-info-renderer, ytm-slim-owner-renderer' },
    {
      feature: 'description',
      selector: '#description.ytd-watch-metadata, ytd-expander.ytd-video-secondary-info-renderer, .slim-video-metadata-header-content > c3-icon, .slim-video-metadata-info',
    },
    { feature: 'header', selector: '#guide-spacer, #masthead-container, .mobile-topbar-header' },
    { feature: 'notifications', selector: '#buttons.ytd-masthead > ytd-notification-topbar-button-renderer.ytd-masthead, ytd-notification-topbar-button-shape-renderer' },
    {
      feature: 'inapt_search',
      selector: '#primary > .ytd-two-column-search-results-renderer ytd-horizontal-card-list-renderer, #primary > .ytd-two-column-search-results-renderer ytd-shelf-renderer',
    },
    {
      feature: 'trending',
      selector: '.yt-simple-endpoint[href^="/feed/explore"], .yt-simple-endpoint[href^="/feed/trending"], ytd-browse[page-subtype=trending], ytd-guide-section-renderer:has(.yt-simple-endpoint[href^="/feed/storefront"]), div[tab-identifier=FEexplore], div[tab-identifier=FEtrending], ytm-pivot-bar-renderer > ytm-pivot-bar-item-renderer:has(.pivot-trending)',
    },
    { feature: 'more_from_youtube', selector: '#sections > ytd-guide-section-renderer:nth-last-child(2)' },
    {
      feature: 'subscriptions',
      selector: '.yt-simple-endpoint[href^="/feed/subscriptions"], ytd-browse[page-subtype=subscriptions], ytd-guide-section-renderer:has(.yt-simple-endpoint[href^="/feed/subscriptions"]), div[tab-identifier=FEsubscriptions], ytm-pivot-bar-renderer > ytm-pivot-bar-item-renderer:has(.pivot-subs)',
    },
    { feature: 'content', selector: 'ytd-watch-flexy, ytm-watch', on: ['content'] },
    { feature: 'search', selector: 'ytd-search, ytm-search', on: ['search'] },
    { feature: 'studio', selector: 'ytcp-app, ytd-browse', on: ['studio'] },
    {
      feature: 'promos',
      selector: '#masthead-ad.ytd-rich-grid-renderer.style-scope, div#home-page-skeleton, paper-dialog > ytd-single-option-survey-renderer[dialog], ytd-mealbar-promo-renderer[dialog], ytd-primetime-promo-renderer, #surveys, .mealbar-promo-renderer',
    },
  ],
  examples: [
    ['https://www.youtube.com/', 'feed'],
    ['https://www.youtube.com/feed/subscriptions', 'feed'],
    ['https://www.youtube.com/feed/notifications', 'feed'],
    ['https://www.youtube.com/@somechannel/videos', 'feed'],
    ['https://www.youtube.com/watch?v=dQw4w9WgXcQ', 'content'],
    ['https://www.youtube.com/watch?list=abc&v=dQw4w9WgXcQ', 'content'],
    ['https://www.youtube.com/watch?v=short', 'feed'],
    ['https://youtu.be/dQw4w9WgXcQ', 'content'],
    ['https://youtu.be/', 'feed'],
    ['https://www.youtube.com/live/dQw4w9WgXcQ', 'content'],
    ['https://www.youtube.com/shorts/dQw4w9WgXcQ', 'shorts'],
    ['https://www.youtube.com/results?search_query=rust', 'search'],
    ['https://studio.youtube.com/', 'studio'],
    ['https://studio.youtube.com/channel/123/videos', 'studio'],
    ['https://www.youtube.com/account', 'essentials'],
    ['https://music.youtube.com/results?search_query=music', 'feed'],
  ],
  android: {
    packages: ['com.google.android.youtube'],
    screens: [
      // The Shorts player: back out of it.
      {
        feature: 'shorts',
        match: [{ viewId: 'com.google.android.youtube:id/reel_recycler' }],
        action: 'back',
        maxTested: '19.x',
      },
      // Shorts shelves in the home feed and search results.
      {
        feature: 'shorts',
        match: [{ viewId: 'com.google.android.youtube:id/reel_shelf_header' }],
        action: 'overlay',
        hideNodes: [{ viewId: 'com.google.android.youtube:id/reel_shelf_header' }],
        maxTested: '19.x',
      },
      // The home video grid; search and videos you open stay usable.
      {
        feature: 'feed',
        match: [{ contentDesc: '^Home$', selected: true }],
        action: 'overlay',
        maxTested: '19.x',
      },
      {
        feature: 'subscriptions',
        match: [{ contentDesc: '^Subscriptions$', selected: true }],
        action: 'overlay',
        maxTested: '19.x',
      },
    ],
  },
});
