import { defineSite } from '../types.js';

export default defineSite({
  id: 'youtube',
  label: 'YouTube',
  hosts: ['youtube.com', 'youtu.be'],
  appHosts: ['youtube.com', 'www.youtube.com', 'm.youtube.com', 'studio.youtube.com', 'youtu.be'],
  networkDomains: ['ytimg.com', 'googlevideo.com', 'ggpht.com'],
  features: [
    { id: 'content', label: 'Videos you open directly', default: 'allow' },
    { id: 'shorts', label: 'Shorts you open directly', default: 'allow' },
    { id: 'comments', label: 'Comments', default: 'allow' },
    { id: 'search', label: 'Search', default: 'allow' },
    { id: 'notifications', label: 'Notifications', default: 'allow' },
    { id: 'studio', label: 'YouTube Studio & uploads', default: 'allow' },
    { id: 'feed', label: 'Home, subscriptions & trending', description: 'The video grids. The pages stay usable for search.', default: 'block' },
    { id: 'recommendations', label: 'Recommended & up next', description: 'The sidebar, end screens, and recommended shelves in search.', default: 'block' },
    { id: 'channels', label: 'Channel pages', default: 'block' },
    { id: 'essentials', label: 'Sign-in & account', default: 'allow', locked: true },
  ],
  routes: [
    { feature: 'studio', host: 'studio.youtube.com' },
    { feature: 'content', host: 'youtu.be', path: '^/([-_a-z0-9]{11})$' },
    { feature: 'content', path: '^/watch$', query: { v: '^[-_a-zA-Z0-9]{11}$' }, judge: { contentSelector: 'ytd-watch-metadata, #above-the-fold' } },
    { feature: 'content', path: '^/live/([-_a-z0-9]{11})$' },
    { feature: 'shorts', path: '^/shorts/([-_a-z0-9]{11})$' },
    { feature: 'search', path: '^/results$', query: { search_query: '^[^&#]+$' } },
    { feature: 'notifications', path: '^/feed/notifications$' },
    { feature: 'studio', path: '^/upload$' },
    { feature: 'essentials', path: '^/(?:account(?:_[^/]+)?|signin|logout|premium|paid_memberships)(?:/.*)?$' },
    { feature: 'channels', path: '^/(?:@[^/]+|channel/[^/]+|c/[^/]+|user/[^/]+)(?:/.*)?$' },
  ],
  fallbackFeature: 'feed',
  elements: [
    { feature: 'feed', selector: 'ytd-browse, ytm-browse', on: ['feed'] },
    {
      feature: 'recommendations',
      selector: '#secondary, #related, ytd-watch-next-secondary-results-renderer, .ytp-endscreen-content, .ytp-ce-element, .ytp-autonav-endscreen-countdown-overlay, ytd-compact-video-renderer, ytd-reel-shelf-renderer, ytd-rich-shelf-renderer, #navigation-button-up, #navigation-button-down',
      on: ['content', 'shorts'],
    },
    { feature: 'recommendations', selector: 'ytd-search ytd-shelf-renderer, ytd-search ytd-reel-shelf-renderer, ytd-search ytd-horizontal-card-list-renderer', on: ['search'] },
    { feature: 'comments', selector: 'ytd-comments#comments, ytm-comment-section-renderer' },
    { feature: 'content', selector: 'ytd-watch-flexy, ytm-watch', on: ['content'] },
    { feature: 'shorts', selector: 'ytd-shorts', on: ['shorts'] },
    { feature: 'shorts', selector: 'ytd-reel-shelf-renderer, ytd-rich-shelf-renderer[is-shorts], ytd-guide-entry-renderer:has(a[title="Shorts"]), ytd-mini-guide-entry-renderer[aria-label="Shorts"]' },
    { feature: 'search', selector: 'ytd-search, ytm-search', on: ['search'] },
    { feature: 'notifications', selector: 'ytd-notification-topbar-button-renderer' },
    { feature: 'notifications', selector: 'ytd-browse, ytm-browse', on: ['notifications'] },
    { feature: 'studio', selector: 'ytcp-app, ytd-browse', on: ['studio'] },
    { feature: 'channels', selector: 'ytd-browse, ytm-browse', on: ['channels'] },
  ],
  examples: [
    ['https://www.youtube.com/', 'feed'],
    ['https://www.youtube.com/feed/subscriptions', 'feed'],
    ['https://www.youtube.com/watch?v=dQw4w9WgXcQ', 'content'],
    ['https://www.youtube.com/watch?list=abc&v=dQw4w9WgXcQ', 'content'],
    ['https://www.youtube.com/watch?v=short', 'feed'],
    ['https://youtu.be/dQw4w9WgXcQ', 'content'],
    ['https://youtu.be/', 'feed'],
    ['https://www.youtube.com/live/dQw4w9WgXcQ', 'content'],
    ['https://www.youtube.com/shorts/dQw4w9WgXcQ', 'shorts'],
    ['https://www.youtube.com/results?search_query=rust', 'search'],
    ['https://www.youtube.com/feed/notifications', 'notifications'],
    ['https://studio.youtube.com/', 'studio'],
    ['https://studio.youtube.com/channel/123/videos', 'studio'],
    ['https://www.youtube.com/account', 'essentials'],
    ['https://www.youtube.com/@somechannel/videos', 'channels'],
    ['https://music.youtube.com/results?search_query=music', 'feed'],
  ],
  android: {
    packages: ['com.google.android.youtube'],
    screens: [
      // The Shorts player: back out of it.
      {
        feature: 'shorts',
        match: [{ viewId: 'com.google.android.youtube:id/reel_recycler' }],
        action: 'back',
        maxTested: '19.x',
      },
      // Shorts shelves in the home feed and search results.
      {
        feature: 'shorts',
        match: [{ viewId: 'com.google.android.youtube:id/reel_shelf_header' }],
        action: 'overlay',
        hideNodes: [{ viewId: 'com.google.android.youtube:id/reel_shelf_header' }],
        maxTested: '19.x',
      },
      // The home / subscriptions video grids; search and videos you open stay usable.
      {
        feature: 'feed',
        match: [{ contentDesc: '^(Home|Subscriptions)$', selected: true }],
        action: 'overlay',
        maxTested: '19.x',
      },
    ],
  },
});
