import { defineSite } from '../types.js';

export default defineSite({
  id: 'youtube',
  label: 'YouTube',
  hosts: ['youtube.com', 'youtu.be'],
  appHosts: ['youtube.com', 'www.youtube.com', 'm.youtube.com', 'studio.youtube.com', 'youtu.be'],
  networkDomains: ['ytimg.com', 'googlevideo.com', 'ggpht.com'],
  features: [
    { id: 'content', label: 'Videos you open directly', default: 'allow' },
    { id: 'shorts', label: 'Shorts you open directly', default: 'allow' },
    { id: 'comments', label: 'Comments', default: 'allow' },
    { id: 'search', label: 'Search', default: 'allow' },
    { id: 'notifications', label: 'Notifications', default: 'allow' },
    { id: 'studio', label: 'YouTube Studio & uploads', default: 'allow' },
    { id: 'feed', label: 'Home, subscriptions & trending', default: 'block' },
    { id: 'recommendations', label: 'Recommended & up next', description: 'The sidebar, end screens, and autoplaying into another video.', default: 'block' },
    { id: 'channels', label: 'Channel pages', default: 'block' },
    { id: 'essentials', label: 'Sign-in & account', default: 'allow', locked: true },
  ],
  routes: [
    { feature: 'studio', host: 'studio.youtube.com' },
    { feature: 'content', host: 'youtu.be', path: '^/([-_a-z0-9]{11})$', item: 1 },
    { feature: 'content', path: '^/watch$', query: { v: '^[-_a-zA-Z0-9]{11}$' }, item: 'v', judge: { contentSelector: 'ytd-watch-metadata, #above-the-fold' } },
    { feature: 'content', path: '^/live/([-_a-z0-9]{11})$', item: 1 },
    { feature: 'shorts', path: '^/shorts/([-_a-z0-9]{11})$', item: 1 },
    { feature: 'search', path: '^/results$', query: { search_query: '^[^&#]+$' } },
    { feature: 'notifications', path: '^/feed/notifications$' },
    { feature: 'studio', path: '^/upload$' },
    { feature: 'essentials', path: '^/(?:account(?:_[^/]+)?|signin|logout|premium|paid_memberships)(?:/.*)?$' },
    { feature: 'channels', path: '^/(?:@[^/]+|channel/[^/]+|c/[^/]+|user/[^/]+)(?:/.*)?$' },
  ],
  fallbackFeature: 'feed',
  hops: { feature: 'recommendations' },
  elements: [
    {
      feature: 'recommendations',
      selector: '#secondary, #related, ytd-watch-next-secondary-results-renderer, .ytp-endscreen-content, .ytp-ce-element, ytd-compact-video-renderer, ytd-reel-shelf-renderer, ytd-rich-shelf-renderer',
      on: ['content', 'shorts'],
    },
    { feature: 'comments', selector: 'ytd-comments#comments' },
  ],
  entryPoints: [
    { feature: 'search', label: 'Search YouTube', url: 'https://www.youtube.com/results', param: 'search_query' },
    { feature: 'studio', label: 'Studio', url: 'https://studio.youtube.com/' },
  ],
  examples: [
    ['https://www.youtube.com/', 'feed'],
    ['https://www.youtube.com/feed/subscriptions', 'feed'],
    ['https://www.youtube.com/watch?v=dQw4w9WgXcQ', 'content'],
    ['https://www.youtube.com/watch?list=abc&v=dQw4w9WgXcQ', 'content'],
    ['https://www.youtube.com/watch?v=short', 'feed'],
    ['https://youtu.be/dQw4w9WgXcQ', 'content'],
    ['https://youtu.be/', 'feed'],
    ['https://www.youtube.com/live/dQw4w9WgXcQ', 'content'],
    ['https://www.youtube.com/shorts/dQw4w9WgXcQ', 'shorts'],
    ['https://www.youtube.com/results?search_query=rust', 'search'],
    ['https://www.youtube.com/feed/notifications', 'notifications'],
    ['https://studio.youtube.com/', 'studio'],
    ['https://studio.youtube.com/channel/123/videos', 'studio'],
    ['https://www.youtube.com/account', 'essentials'],
    ['https://www.youtube.com/@somechannel/videos', 'channels'],
    ['https://music.youtube.com/results?search_query=music', 'feed'],
  ],
});
