//! uniffi facade over [`talysman_engine::Engine`] for Talysman for Android. Mirrors the wasm
//! facade: every argument and result is a JSON string of an engine type (see
//! packages/shared/src/generated for the shapes), so the Kotlin surface stays tiny and all
//! decisions stay in Rust. Kotlin bindings are generated by `uniffi-bindgen` (see
//! apps/android/engine/build.gradle.kts).

use std::sync::{Arc, Mutex};

use serde::de::DeserializeOwned;
use talysman_engine::engine::{Command, PopupTarget};
use talysman_engine::model::EngineState;
use talysman_engine::pairing::{self, SaltedHash};
use talysman_engine::policy::AppRef;
use talysman_engine::{Auth, Ctx, Engine};

uniffi::setup_scaffolding!();

#[derive(Debug, uniffi::Error)]
pub enum EngineFfiError {
    /// An engine refusal or bad input: `code` is a service error code (KEY_REQUIRED, …).
    Refused { code: String, detail: String },
}

impl std::fmt::Display for EngineFfiError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            EngineFfiError::Refused { code, detail } => write!(f, "{code}: {detail}"),
        }
    }
}

impl std::error::Error for EngineFfiError {}

fn parse<T: DeserializeOwned>(json: &str, what: &str) -> Result<T, EngineFfiError> {
    serde_json::from_str(json).map_err(|e| EngineFfiError::Refused { code: "BAD_REQUEST".into(), detail: format!("Bad {what}: {e}") })
}

fn to_json<T: serde::Serialize>(value: &T) -> String {
    serde_json::to_string(value).expect("engine types serialize")
}

#[derive(uniffi::Object)]
pub struct EngineHandle {
    inner: Mutex<Engine>,
}

impl EngineHandle {
    fn with<T>(&self, f: impl FnOnce(&mut Engine) -> T) -> T {
        let mut guard = self.inner.lock().unwrap_or_else(|e| e.into_inner());
        f(&mut guard)
    }
}

#[uniffi::export]
impl EngineHandle {
    /// Load persisted `EngineState` JSON.
    #[uniffi::constructor]
    pub fn load(state_json: String) -> Result<Arc<Self>, EngineFfiError> {
        let engine = Engine::load(&state_json).map_err(|e| EngineFfiError::Refused { code: e.code, detail: e.message })?;
        Ok(Arc::new(EngineHandle { inner: Mutex::new(engine) }))
    }

    /// A fresh engine with no profiles.
    #[uniffi::constructor]
    pub fn empty(device_id: String) -> Arc<Self> {
        Arc::new(EngineHandle { inner: Mutex::new(Engine::new(EngineState::new(&device_id))) })
    }

    pub fn export_state(&self) -> String {
        self.with(|e| e.export())
    }

    pub fn gate(&self, command_json: String, ctx_json: String) -> Result<String, EngineFfiError> {
        let command: Command = parse(&command_json, "command")?;
        let ctx: Ctx = parse(&ctx_json, "ctx")?;
        Ok(self.with(|e| to_json(&e.gate(&command, &ctx))))
    }

    /// Apply a command. `auth_json` is `{"kind":"none"}` or `{"kind":"keyVerified","keyId":…}` —
    /// only construct the latter right after an NFC/QR key scan verified in-process.
    pub fn apply(&self, command_json: String, auth_json: String, ctx_json: String) -> Result<String, EngineFfiError> {
        let command: Command = parse(&command_json, "command")?;
        let auth: Auth = parse(&auth_json, "auth")?;
        let ctx: Ctx = parse(&ctx_json, "ctx")?;
        self.with(|e| e.apply(command, auth, &ctx))
            .map(|applied| to_json(&applied))
            .map_err(|e| EngineFfiError::Refused { code: e.code, detail: e.message })
    }

    pub fn tick(&self, ctx_json: String) -> Result<String, EngineFfiError> {
        let ctx: Ctx = parse(&ctx_json, "ctx")?;
        Ok(self.with(|e| to_json(&e.tick(&ctx))))
    }

    pub fn snapshot(&self, ctx_json: String) -> Result<String, EngineFfiError> {
        let ctx: Ctx = parse(&ctx_json, "ctx")?;
        Ok(self.with(|e| to_json(&e.snapshot(&ctx))))
    }

    pub fn effective(&self, ctx_json: String) -> Result<String, EngineFfiError> {
        let ctx: Ctx = parse(&ctx_json, "ctx")?;
        Ok(self.with(|e| to_json(&e.effective(&ctx))))
    }

    /// Decision for a foreground Android app (`AppRef` JSON with `androidPackage`).
    pub fn decide_app(&self, app_json: String, ctx_json: String) -> Result<String, EngineFfiError> {
        let app: AppRef = parse(&app_json, "app")?;
        let ctx: Ctx = parse(&ctx_json, "ctx")?;
        Ok(self.with(|e| to_json(&e.decide_app(&app, &ctx))))
    }

    /// Decision for a browser page. `extension_capable`: the browser runs the Talysman
    /// extension (Firefox with the bridge connected), so soft rules are left to it.
    pub fn decide_url(&self, url: String, extension_capable: bool, ctx_json: String) -> Result<String, EngineFfiError> {
        let ctx: Ctx = parse(&ctx_json, "ctx")?;
        Ok(self.with(|e| to_json(&e.decide_url(&url, extension_capable, &ctx))))
    }

    pub fn popup_info(&self, target_json: String, ctx_json: String) -> Result<String, EngineFfiError> {
        let target: PopupTarget = parse(&target_json, "target")?;
        let ctx: Ctx = parse(&ctx_json, "ctx")?;
        Ok(self.with(|e| to_json(&e.popup_info(&target, &ctx))))
    }

    /// The `state` frame for the Firefox extension over the loopback bridge — the same frame the
    /// desktop native-messaging hosts send (`natmsg_frames::state_frame`). `hello_json` is the
    /// extension's `hello` (its site capability and known site ids).
    pub fn extension_state_frame(&self, ctx_json: String, hello_json: String) -> Result<String, EngineFfiError> {
        let ctx: Ctx = parse(&ctx_json, "ctx")?;
        let hello: serde_json::Value = parse(&hello_json, "hello")?;
        let caps = talysman_common::natmsg_frames::ExtensionCaps::from_hello(&hello);
        let blocking = self.with(|e| {
            let effective = e.effective(&ctx);
            talysman_common::natmsg_frames::Blocking {
                active: effective.active(),
                policy: talysman_engine::effective::flatten_network(&effective.layers),
                handshake_enabled: false,
                // No AI filtering on Android (spec answer 20): judged rules resolve to fallback.
                smart_filtering_enabled: false,
            }
        });
        Ok(to_json(&talysman_common::natmsg_frames::state_frame(&blocking, &caps)))
    }

    /// The domains a DNS sinkhole should refuse (optional VPN mode).
    pub fn sinkhole_domains(&self, ctx_json: String) -> Result<Vec<String>, EngineFfiError> {
        let ctx: Ctx = parse(&ctx_json, "ctx")?;
        Ok(self.with(|e| talysman_engine::effective::dns_sinkhole_domains(&e.effective(&ctx).layers).into_iter().collect()))
    }
}

/// Salt-and-hash a key secret (NFC NDEF secret or QR payload) for storage. Returns `SaltedHash` JSON.
#[uniffi::export]
pub fn hash_key_secret(secret: Vec<u8>, salt: Vec<u8>) -> String {
    to_json(&pairing::hash_secret_with_salt(&secret, &salt))
}

/// Check a scanned secret against a stored `SaltedHash` JSON.
#[uniffi::export]
pub fn verify_key_secret(secret: Vec<u8>, stored_json: String) -> bool {
    serde_json::from_str::<SaltedHash>(&stored_json).is_ok_and(|stored| pairing::verify_secret(&secret, &stored))
}

/// The extension's `service-request` frame, if allowed: `{"requestId","method","params"}` JSON.
/// Same allowlist the desktop hosts enforce (popup info + keyless pool-unlock commands).
#[uniffi::export]
pub fn relay_request(frame_json: String) -> Option<String> {
    let frame: serde_json::Value = serde_json::from_str(&frame_json).ok()?;
    let (request_id, method, params) = talysman_common::natmsg_frames::relay_request(&frame)?;
    Some(to_json(&serde_json::json!({ "requestId": request_id, "method": method, "params": params })))
}

/// The `service-response` frame for a relayed request. `response_json` is `{"ok":true,"result":…}`
/// or `{"ok":false,"code":…,"message":…}`.
#[uniffi::export]
pub fn relay_response_frame(request_id_json: String, response_json: String) -> String {
    let request_id: serde_json::Value = serde_json::from_str(&request_id_json).unwrap_or(serde_json::Value::Null);
    let response: serde_json::Value = serde_json::from_str(&response_json).unwrap_or(serde_json::Value::Null);
    to_json(&talysman_common::natmsg_frames::relay_response_frame(&request_id, &response))
}

/// `site:feature` for a URL the catalog owns (debug screens and tests).
#[uniffi::export]
pub fn classify_url(url: String) -> Option<String> {
    talysman_engine::site_catalog::classify_url(&url).map(|c| format!("{}:{}", c.site, c.feature))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn round_trips_commands_through_json() {
        let engine = EngineHandle::empty("android".into());
        let ctx = r#"{"now":{"epochMs":1790000000000,"utcOffsetS":0},"hasPairedKeys":true}"#.to_string();
        let upsert = r#"{"type":"upsertProfile","profile":{"id":"p","name":"P","color":"c","config":{"policy":{"blockedDomains":[],"allowedDomains":[],"defaultAction":"allow","judge":null,"apps":[{"androidPackage":"com.instagram.android","label":"Instagram"}],"enabledPremadeLists":[],"sites":{}}}}}"#;
        engine.apply(upsert.into(), r#"{"kind":"none"}"#.into(), ctx.clone()).unwrap();
        engine.apply(r#"{"type":"setLatch","profileId":"p","on":true}"#.into(), r#"{"kind":"none"}"#.into(), ctx.clone()).unwrap();
        let decision = engine.decide_app(r#"{"androidPackage":"com.instagram.android","label":"Instagram"}"#.into(), ctx.clone()).unwrap();
        assert!(decision.contains(r#""kind":"hard""#), "{decision}");
        let refused = engine.apply(r#"{"type":"startOverrideAll"}"#.into(), r#"{"kind":"none"}"#.into(), ctx).unwrap_err();
        assert!(matches!(refused, EngineFfiError::Refused { code, .. } if code == "KEY_REQUIRED"));
        let stored = hash_key_secret(b"secret".to_vec(), vec![1; 16]);
        assert!(verify_key_secret(b"secret".to_vec(), stored.clone()));
        assert!(!verify_key_secret(b"other".to_vec(), stored));
    }
}
