plugins {
    id("com.android.application")
    id("org.jetbrains.kotlin.android")
    id("org.jetbrains.kotlin.plugin.compose")
    id("org.jetbrains.kotlin.plugin.serialization")
}

// Talysman for Android (spec §6): the blocker. All decisions come from the Rust engine (:engine).

extra["palettePackage"] = "app.talysman.android.ui.theme"
apply(from = rootProject.file("gradle/palette.gradle.kts"))
@Suppress("UNCHECKED_CAST")
val generatedPaletteDir = extra["generatedPaletteDir"] as Provider<Directory>

// The Android half of the site catalog (browsers, guards, in-app screens), generated by
// `pnpm generate:sites` from packages/shared/src/sites.
val androidCatalog = rootProject.file("../../apps/android/blocker/catalog/android-catalog.json")

android {
    namespace = "app.talysman.android"
    compileSdk = 36

    defaultConfig {
        applicationId = "app.talysman.android"
        minSdk = 26
        targetSdk = 36
        versionCode = 1
        versionName = "0.7.0"
    }

    flavorDimensions += "distribution"
    productFlavors {
        // Sideloaded APK: Pro without an account, Device Admin uninstall protection.
        create("sideload") {
            dimension = "distribution"
            buildConfigField("String", "ENTITLEMENT_SOURCE", "\"sideload\"")
            buildConfigField("boolean", "DEVICE_ADMIN", "true")
        }
        // Play Store build: plan from the account; no Device Admin.
        create("play") {
            dimension = "distribution"
            buildConfigField("String", "ENTITLEMENT_SOURCE", "\"server\"")
            buildConfigField("boolean", "DEVICE_ADMIN", "false")
        }
    }

    buildTypes {
        release {
            isMinifyEnabled = false
            // A real release key comes from local-credentials/ once distribution starts.
            signingConfig = signingConfigs.getByName("debug")
        }
    }

    buildFeatures {
        compose = true
        buildConfig = true
    }

    sourceSets.getByName("main").apply {
        java.srcDir(generatedPaletteDir.map { it.dir("kotlin") })
        res.srcDir(generatedPaletteDir.map { it.dir("res") })
        assets.srcDir(androidCatalog.parentFile)
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }

    kotlinOptions {
        jvmTarget = "17"
    }

    testOptions {
        unitTests.isReturnDefaultValues = true
    }
}

dependencies {
    implementation(project(":engine"))

    implementation(platform("androidx.compose:compose-bom:2024.12.01"))
    implementation("androidx.core:core-ktx:1.15.0")
    implementation("androidx.lifecycle:lifecycle-runtime-ktx:2.8.7")
    implementation("androidx.lifecycle:lifecycle-runtime-compose:2.8.7")
    implementation("androidx.lifecycle:lifecycle-service:2.8.7")
    implementation("androidx.activity:activity-compose:1.9.3")
    implementation("androidx.compose.ui:ui")
    implementation("androidx.compose.ui:ui-graphics")
    implementation("androidx.compose.ui:ui-tooling-preview")
    implementation("androidx.compose.material3:material3")
    implementation("org.jetbrains.kotlinx:kotlinx-serialization-json:1.7.3")
    implementation("org.jetbrains.kotlinx:kotlinx-coroutines-android:1.9.0")

    // QR keys: generation and decoding (pure Java, no Play Services) + CameraX for scanning.
    implementation("com.google.zxing:core:3.5.3")
    implementation("androidx.camera:camera-camera2:1.4.1")
    implementation("androidx.camera:camera-lifecycle:1.4.1")
    implementation("androidx.camera:camera-view:1.4.1")

    // Firefox extension bridge (spec §6.8): a loopback WebSocket server.
    implementation("org.java-websocket:Java-WebSocket:1.5.7")

    testImplementation("junit:junit:4.13.2")
    // Desktop JNA (the aar has Android natives only) so JVM tests can load a host engine build.
    testImplementation("net.java.dev.jna:jna:5.15.0")
    debugImplementation("androidx.compose.ui:ui-tooling")
}
