//! Persisted engine state (schema 6). Every type here crosses the wire to the desktop UI (via the
//! daemon), to Android (via uniffi JSON), and to TypeScript (generated by ts-rs), so field names
//! are camelCase and enums are internally tagged with `kind`.

use serde::{Deserialize, Serialize};

use crate::policy::{AppRef, Policy};
use crate::time::Weekday;

pub const SCHEMA_VERSION: u32 = 6;
pub const EMERGENCY_LIFETIME_LIMIT: u8 = 5;
pub const MAX_PROFILE_NAME_LENGTH: usize = 40;
pub const MAX_POOL_UNLOCKS_PER_DAY: u8 = 20;
pub const MAX_POOL_UNLOCK_MINUTES: u16 = 120;
pub const MAX_FRICTION_SECS: u16 = 60;
pub const MAX_TIMED_OVERRIDE_MINUTES: u16 = 720;
/// A friction-complete pending pool unlock that isn't confirmed within this long is discarded.
pub const PENDING_UNLOCK_TTL_MS: i64 = 10 * 60_000;
/// Fired one-shot events stay visible ("Done") for this long.
pub const FIRED_ONE_SHOT_RETENTION_MS: i64 = 7 * 24 * 60 * 60_000;
/// Non-breaking journal entries are pruned after this long; breaking/emergency entries are kept.
pub const JOURNAL_RETENTION_MS: i64 = 90 * 24 * 60 * 60_000;

pub type ProfileId = String;

#[derive(Clone, Debug, Serialize, Deserialize, PartialEq, Eq)]
#[cfg_attr(feature = "ts", derive(ts_rs::TS))]
#[serde(rename_all = "camelCase")]
pub struct EngineState {
    pub schema: u32,
    pub device_id: String,
    pub profiles: Vec<Profile>,
    /// The profile the "turn focus on" shortcuts (tray, focus CLI, legacy `enableFocus`) latch on.
    #[serde(default)]
    pub default_profile_id: Option<ProfileId>,
    #[serde(default)]
    pub overrides: Overrides,
    #[serde(default)]
    pub pool_usage: Vec<PoolUsage>,
    #[serde(default)]
    pub pending_unlocks: Vec<PendingPoolUnlock>,
    #[serde(default)]
    pub journal: Vec<JournalEntry>,
    #[serde(default)]
    #[cfg_attr(feature = "ts", ts(type = "number"))]
    pub journal_seq: u64,
    #[serde(default)]
    #[cfg_attr(feature = "ts", ts(type = "number"))]
    pub last_evaluated_ms: i64,
    /// Local date ("YYYY-MM-DD") a profile was first ever active; the streak counts from here
    /// until the first break.
    #[serde(default)]
    pub first_enabled_local_date: Option<String>,
    /// Bumped whenever the effective (enforced) policy changes.
    #[serde(default)]
    #[cfg_attr(feature = "ts", ts(type = "number"))]
    pub generation: u64,
}

#[derive(Clone, Debug, Serialize, Deserialize, PartialEq, Eq)]
#[cfg_attr(feature = "ts", derive(ts_rs::TS))]
#[serde(rename_all = "camelCase")]
pub struct Profile {
    pub id: ProfileId,
    pub name: String,
    pub color: String,
    #[serde(default)]
    #[cfg_attr(feature = "ts", ts(type = "number"))]
    pub created_at_ms: i64,
    #[serde(default)]
    pub config: ProfileConfig,
    #[serde(default)]
    pub latch: Latch,
}

/// Everything a profile blocks and when. `policy` is the web/app/soft-rule model the desktop has
/// always used (`blockedDomains`, `allowedDomains`, `defaultAction`, `judge`, blacklisted `apps`,
/// premade lists, and catalog `sites` soft rules); the rest is new in schema 6.
#[derive(Clone, Debug, Default, Serialize, Deserialize, PartialEq, Eq)]
#[cfg_attr(feature = "ts", derive(ts_rs::TS))]
#[serde(rename_all = "camelCase")]
pub struct ProfileConfig {
    #[serde(default)]
    pub policy: Policy,
    /// Blacklist: `policy.apps` are blocked. Whitelist: every app except `allowedApps` (and the
    /// platform's always-allowed system set) is blocked; `policy.apps` are still hard-blocked.
    #[serde(default)]
    pub app_mode: BlockMode,
    #[serde(default)]
    pub allowed_apps: Vec<AppRef>,
    #[serde(default)]
    pub pools: Vec<Pool>,
    #[serde(default)]
    pub schedule: Vec<ScheduleRule>,
    #[serde(default)]
    pub one_shots: Vec<OneShotEvent>,
}

#[derive(Clone, Copy, Debug, Default, Serialize, Deserialize, PartialEq, Eq)]
#[cfg_attr(feature = "ts", derive(ts_rs::TS))]
#[serde(rename_all = "lowercase")]
pub enum BlockMode {
    #[default]
    Blacklist,
    Whitelist,
}

#[derive(Clone, Copy, Debug, Serialize, Deserialize, PartialEq, Eq)]
#[cfg_attr(feature = "ts", derive(ts_rs::TS))]
#[serde(rename_all = "camelCase")]
pub enum LatchSource {
    User,
    AtRule,
    OneShot,
    Migration,
}

/// A profile's manual on/off switch. Active ⇔ latch on OR an unsuppressed window covers now.
#[derive(Clone, Debug, Default, Serialize, Deserialize, PartialEq, Eq)]
#[cfg_attr(feature = "ts", derive(ts_rs::TS))]
#[serde(tag = "state", rename_all = "camelCase")]
pub enum Latch {
    #[serde(rename_all = "camelCase")]
    On {
        #[cfg_attr(feature = "ts", ts(type = "number"))]
        since_ms: i64,
        source: LatchSource,
    },
    #[default]
    Off,
}

impl Latch {
    pub fn is_on(&self) -> bool {
        matches!(self, Latch::On { .. })
    }
}

/// Something that can be blocked and therefore pooled or exempted.
#[derive(Clone, Debug, Serialize, Deserialize, PartialEq, Eq)]
#[cfg_attr(feature = "ts", derive(ts_rs::TS))]
#[serde(tag = "kind", rename_all = "camelCase")]
pub enum ItemRef {
    /// A domain pattern as the user wrote it ("reddit.com", "*.reddit.com").
    Domain { domain: String },
    App { app: AppRef },
    /// A site-catalog entry: its web hosts *and* its Android packages.
    Catalog { id: String },
}

#[derive(Clone, Debug, Serialize, Deserialize, PartialEq, Eq)]
#[cfg_attr(feature = "ts", derive(ts_rs::TS))]
#[serde(tag = "kind", rename_all = "camelCase")]
pub enum Friction {
    None,
    Countdown { secs: u16 },
    Breathing { secs: u16 },
}

impl Default for Friction {
    fn default() -> Self {
        Friction::None
    }
}

impl Friction {
    pub fn secs(&self) -> u16 {
        match self {
            Friction::None => 0,
            Friction::Countdown { secs } | Friction::Breathing { secs } => *secs,
        }
    }
}

/// ScreenZen-style override pool: `unlocks_per_day` keyless unlocks of `unlock_minutes` each,
/// shared by every item in the pool.
#[derive(Clone, Debug, Serialize, Deserialize, PartialEq, Eq)]
#[cfg_attr(feature = "ts", derive(ts_rs::TS))]
#[serde(rename_all = "camelCase")]
pub struct Pool {
    pub id: String,
    pub name: String,
    #[serde(default)]
    pub items: Vec<ItemRef>,
    pub unlocks_per_day: u8,
    pub unlock_minutes: u16,
    #[serde(default)]
    pub friction: Friction,
}

#[derive(Clone, Copy, Debug, Serialize, Deserialize, PartialEq, Eq)]
#[cfg_attr(feature = "ts", derive(ts_rs::TS))]
#[serde(rename_all = "lowercase")]
pub enum OnOff {
    On,
    Off,
}

#[derive(Clone, Debug, Serialize, Deserialize, PartialEq, Eq)]
#[cfg_attr(feature = "ts", derive(ts_rs::TS))]
#[serde(tag = "kind", rename_all = "camelCase")]
pub enum ScheduleRule {
    /// The profile is active during the window. `end <= start` crosses midnight; `start == end`
    /// never matches. `locked`: the key can't end or override it (only an emergency unlock can).
    Window {
        id: String,
        days: Vec<Weekday>,
        /// "HH:MM"
        start: String,
        /// "HH:MM"
        end: String,
        #[serde(default)]
        locked: bool,
    },
    /// Recurring latch flip: "on at 09:00" / "off at 17:00".
    At {
        id: String,
        days: Vec<Weekday>,
        /// "HH:MM"
        at: String,
        action: OnOff,
    },
}

impl ScheduleRule {
    pub fn id(&self) -> &str {
        match self {
            ScheduleRule::Window { id, .. } | ScheduleRule::At { id, .. } => id,
        }
    }
}

#[derive(Clone, Debug, Serialize, Deserialize, PartialEq, Eq)]
#[cfg_attr(feature = "ts", derive(ts_rs::TS))]
#[serde(rename_all = "camelCase")]
pub struct OneShotEvent {
    pub id: String,
    #[cfg_attr(feature = "ts", ts(type = "number"))]
    pub at_ms: i64,
    pub action: OnOff,
    #[serde(default)]
    #[cfg_attr(feature = "ts", ts(type = "number | null"))]
    pub fired_at_ms: Option<i64>,
}

/// One concrete occurrence of a window (identity for suppression and emergency bypass).
#[derive(Clone, Debug, Serialize, Deserialize, PartialEq, Eq)]
#[cfg_attr(feature = "ts", derive(ts_rs::TS))]
#[serde(rename_all = "camelCase")]
pub struct WindowOccurrence {
    pub profile_id: ProfileId,
    pub window_id: String,
    #[cfg_attr(feature = "ts", ts(type = "number"))]
    pub start_ms: i64,
    #[cfg_attr(feature = "ts", ts(type = "number"))]
    pub end_ms: i64,
    pub locked: bool,
}

impl WindowOccurrence {
    pub fn same(&self, other: &WindowOccurrence) -> bool {
        self.profile_id == other.profile_id && self.window_id == other.window_id && self.start_ms == other.start_ms
    }
}

#[derive(Clone, Debug, Serialize, Deserialize, PartialEq, Eq)]
#[cfg_attr(feature = "ts", derive(ts_rs::TS))]
#[serde(rename_all = "camelCase")]
pub struct PriorLatch {
    pub profile_id: ProfileId,
    pub latch: Latch,
}

/// Override (1): everything off until re-enabled (also what an emergency unlock does).
#[derive(Clone, Debug, Serialize, Deserialize, PartialEq, Eq)]
#[cfg_attr(feature = "ts", derive(ts_rs::TS))]
#[serde(rename_all = "camelCase")]
pub struct AllOff {
    #[cfg_attr(feature = "ts", ts(type = "number"))]
    pub since_ms: i64,
    #[serde(default)]
    pub emergency: bool,
    #[serde(default)]
    pub prior_latches: Vec<PriorLatch>,
}

/// Override (2): chosen items exempt from every layer, and/or chosen profiles off, until
/// "Re-enable all".
#[derive(Clone, Debug, Serialize, Deserialize, PartialEq, Eq)]
#[cfg_attr(feature = "ts", derive(ts_rs::TS))]
#[serde(rename_all = "camelCase")]
pub struct Exempt {
    #[cfg_attr(feature = "ts", ts(type = "number"))]
    pub since_ms: i64,
    #[serde(default)]
    pub items: Vec<ItemRef>,
    #[serde(default)]
    pub profiles: Vec<ProfileId>,
    #[serde(default)]
    pub prior_latches: Vec<PriorLatch>,
}

/// Override (3): everything off (except locked windows) until `until_ms`.
#[derive(Clone, Debug, Serialize, Deserialize, PartialEq, Eq)]
#[cfg_attr(feature = "ts", derive(ts_rs::TS))]
#[serde(rename_all = "camelCase")]
pub struct TimedOff {
    #[cfg_attr(feature = "ts", ts(type = "number"))]
    pub since_ms: i64,
    #[cfg_attr(feature = "ts", ts(type = "number"))]
    pub until_ms: i64,
}

#[derive(Clone, Debug, Default, Serialize, Deserialize, PartialEq, Eq)]
#[cfg_attr(feature = "ts", derive(ts_rs::TS))]
#[serde(rename_all = "camelCase")]
pub struct Overrides {
    #[serde(default)]
    pub all_off: Option<AllOff>,
    #[serde(default)]
    pub exempt: Option<Exempt>,
    #[serde(default)]
    pub timed: Option<TimedOff>,
    /// In-progress window occurrences switched off by override (1)/(2); they end on their own.
    #[serde(default)]
    pub suppressed: Vec<WindowOccurrence>,
    /// Locked window occurrences ended early by an emergency unlock.
    #[serde(default)]
    pub locked_bypass: Vec<WindowOccurrence>,
}

impl Overrides {
    pub fn any(&self) -> bool {
        self.all_off.is_some() || self.exempt.is_some() || self.timed.is_some()
    }
}

#[derive(Clone, Debug, Serialize, Deserialize, PartialEq, Eq, PartialOrd, Ord)]
#[cfg_attr(feature = "ts", derive(ts_rs::TS))]
#[serde(rename_all = "camelCase")]
pub struct PoolRef {
    pub profile_id: ProfileId,
    pub pool_id: String,
}

#[derive(Clone, Debug, Serialize, Deserialize, PartialEq, Eq)]
#[cfg_attr(feature = "ts", derive(ts_rs::TS))]
#[serde(rename_all = "camelCase")]
pub struct PoolUsage {
    pub profile_id: ProfileId,
    pub pool_id: String,
    /// Local date the counter belongs to ("YYYY-MM-DD"); an unlock counts against the day it
    /// started.
    pub local_date: String,
    pub used: u8,
    #[serde(default)]
    #[cfg_attr(feature = "ts", ts(type = "number | null"))]
    pub active_until_ms: Option<i64>,
}

#[derive(Clone, Debug, Serialize, Deserialize, PartialEq, Eq)]
#[cfg_attr(feature = "ts", derive(ts_rs::TS))]
#[serde(rename_all = "camelCase")]
pub struct PendingPoolUnlock {
    pub pools: Vec<PoolRef>,
    #[cfg_attr(feature = "ts", ts(type = "number"))]
    pub requested_ms: i64,
    #[cfg_attr(feature = "ts", ts(type = "number"))]
    pub ready_ms: i64,
}

#[derive(Clone, Copy, Debug, Serialize, Deserialize, PartialEq, Eq)]
#[cfg_attr(feature = "ts", derive(ts_rs::TS))]
#[serde(rename_all = "camelCase")]
pub enum OverrideKind {
    AllOff,
    Exempt,
    Timed,
}

#[derive(Clone, Copy, Debug, Serialize, Deserialize, PartialEq, Eq)]
#[cfg_attr(feature = "ts", derive(ts_rs::TS))]
#[serde(rename_all = "camelCase")]
pub enum ChangeSource {
    User,
    Schedule,
    OneShot,
    Emergency,
    Migration,
}

#[derive(Clone, Debug, Serialize, Deserialize, PartialEq, Eq)]
#[cfg_attr(feature = "ts", derive(ts_rs::TS))]
#[serde(tag = "kind", rename_all = "camelCase")]
pub enum JournalKind {
    #[serde(rename_all = "camelCase")]
    ProfileOn { profile_id: ProfileId, source: ChangeSource },
    #[serde(rename_all = "camelCase")]
    ProfileOff { profile_id: ProfileId, source: ChangeSource },
    #[serde(rename_all = "camelCase")]
    OverrideStarted { r#override: OverrideKind },
    #[serde(rename_all = "camelCase")]
    OverrideEnded { r#override: OverrideKind },
    ReenabledAll,
    #[serde(rename_all = "camelCase")]
    Relaxed { profile_id: ProfileId, summary: Vec<String> },
    #[serde(rename_all = "camelCase")]
    ProfileDeleted { profile_id: ProfileId },
    #[serde(rename_all = "camelCase")]
    PoolUnlocked { pools: Vec<PoolRef>, minutes: u16 },
    EmergencyUsed,
    KeyPaired,
    KeyUnpaired,
    /// Written once when upgrading from a v5 state file.
    Migration,
}

/// Append-only, sync-ready event log. Ids are globally unique (`<deviceId>:<seq>`) so a future
/// account sync is a union merge; streak and emergency counts are pure functions of it.
#[derive(Clone, Debug, Serialize, Deserialize, PartialEq, Eq)]
#[cfg_attr(feature = "ts", derive(ts_rs::TS))]
#[serde(rename_all = "camelCase")]
pub struct JournalEntry {
    pub id: String,
    pub device_id: String,
    #[cfg_attr(feature = "ts", ts(type = "number"))]
    pub seq: u64,
    #[cfg_attr(feature = "ts", ts(type = "number"))]
    pub at_ms: i64,
    pub local_date: String,
    /// Whether this entry resets the streak (key overrides, relaxations, emergency unlocks).
    pub breaks_streak: bool,
    pub kind: JournalKind,
}

impl EngineState {
    pub fn new(device_id: &str) -> Self {
        EngineState {
            schema: SCHEMA_VERSION,
            device_id: device_id.to_string(),
            profiles: Vec::new(),
            default_profile_id: None,
            overrides: Overrides::default(),
            pool_usage: Vec::new(),
            pending_unlocks: Vec::new(),
            journal: Vec::new(),
            journal_seq: 0,
            last_evaluated_ms: 0,
            first_enabled_local_date: None,
            generation: 0,
        }
    }

    pub fn profile(&self, id: &str) -> Option<&Profile> {
        self.profiles.iter().find(|p| p.id == id)
    }

    pub fn profile_mut(&mut self, id: &str) -> Option<&mut Profile> {
        self.profiles.iter_mut().find(|p| p.id == id)
    }

    pub fn pool(&self, r: &PoolRef) -> Option<&Pool> {
        self.profile(&r.profile_id)?.config.pools.iter().find(|p| p.id == r.pool_id)
    }
}
