// Generated by scripts/generate-premade-lists.mjs — do not edit by hand.

#[derive(Clone, Copy, Debug, serde::Serialize, serde::Deserialize, PartialEq, Eq, Hash)]
#[cfg_attr(feature = "ts", derive(ts_rs::TS))]
pub enum PremadeListId {
    #[serde(rename = "nsfw")]
    Nsfw,
    #[serde(rename = "shopping")]
    Shopping,
    #[serde(rename = "social")]
    Social,
    #[serde(rename = "gambling")]
    Gambling,
    #[serde(rename = "press")]
    Press,
    #[serde(rename = "games")]
    Games,
    #[serde(rename = "sports")]
    Sports,
    #[serde(rename = "forums")]
    Forums,
    #[serde(rename = "webemail")]
    Webemail,
    #[serde(rename = "blog")]
    Blog,
    #[serde(rename = "streaming")]
    Streaming,
}

pub(crate) const PREMADE_LIST_COUNT: usize = 11;

impl PremadeListId {
    pub(crate) const fn as_index(self) -> usize {
        match self {
            Self::Nsfw => 0,
            Self::Shopping => 1,
            Self::Social => 2,
            Self::Gambling => 3,
            Self::Press => 4,
            Self::Games => 5,
            Self::Sports => 6,
            Self::Forums => 7,
            Self::Webemail => 8,
            Self::Blog => 9,
            Self::Streaming => 10,
        }
    }
}

/// Builds without the `premade` feature (Android without the VPN sinkhole) embed no lists.
#[cfg(not(feature = "premade"))]
pub(crate) fn premade_list_source(_id: PremadeListId) -> &'static str {
    ""
}

#[cfg(feature = "premade")]
pub(crate) fn premade_list_source(id: PremadeListId) -> &'static str {
    match id {
        PremadeListId::Nsfw => include_str!("../resources/premade-lists/nsfw.txt"),
        PremadeListId::Shopping => include_str!("../resources/premade-lists/shopping.txt"),
        PremadeListId::Social => include_str!("../resources/premade-lists/social.txt"),
        PremadeListId::Gambling => include_str!("../resources/premade-lists/gambling.txt"),
        PremadeListId::Press => include_str!("../resources/premade-lists/press.txt"),
        PremadeListId::Games => include_str!("../resources/premade-lists/games.txt"),
        PremadeListId::Sports => include_str!("../resources/premade-lists/sports.txt"),
        PremadeListId::Forums => include_str!("../resources/premade-lists/forums.txt"),
        PremadeListId::Webemail => include_str!("../resources/premade-lists/webemail.txt"),
        PremadeListId::Blog => include_str!("../resources/premade-lists/blog.txt"),
        PremadeListId::Streaming => include_str!("../resources/premade-lists/streaming.txt"),
    }
}

pub(crate) fn premade_list_exemptions(id: PremadeListId) -> &'static [&'static str] {
    match id {
        PremadeListId::Nsfw => &[],
        PremadeListId::Shopping => &["aws.amazon.com", "signin.aws.amazon.com"],
        PremadeListId::Social => &[],
        PremadeListId::Gambling => &[],
        PremadeListId::Press => &[],
        PremadeListId::Games => &[],
        PremadeListId::Sports => &[],
        PremadeListId::Forums => &[],
        PremadeListId::Webemail => &[],
        PremadeListId::Blog => &[],
        PremadeListId::Streaming => &[],
    }
}
