// Generated by scripts/generate-premade-lists.mjs — do not edit by hand.

export type PremadeListId = 'nsfw' | 'shopping' | 'social' | 'gambling' | 'press' | 'games' | 'sports' | 'forums' | 'webemail' | 'blog' | 'streaming';

export interface PremadeListMeta {
  id: PremadeListId;
  label: string;
  description: string;
  domainCount: number;
}

export const PREMADE_LISTS: PremadeListMeta[] = [
  {
    "id": "nsfw",
    "label": "NSFW",
    "description": "Pornography and adult content sites.",
    "domainCount": 428013
  },
  {
    "id": "shopping",
    "label": "Shopping",
    "description": "Online retail and shopping sites.",
    "domainCount": 36778
  },
  {
    "id": "social",
    "label": "Social media",
    "description": "Social networking and social media sites.",
    "domainCount": 887
  },
  {
    "id": "gambling",
    "label": "Gambling",
    "description": "Online casinos and betting sites.",
    "domainCount": 67317
  },
  {
    "id": "press",
    "label": "Press",
    "description": "News and press sites.",
    "domainCount": 4633
  },
  {
    "id": "games",
    "label": "Games",
    "description": "Online games and game distribution sites.",
    "domainCount": 32914
  },
  {
    "id": "sports",
    "label": "Sports",
    "description": "Sports news and content sites.",
    "domainCount": 2309
  },
  {
    "id": "forums",
    "label": "Forums",
    "description": "Discussion forums and message boards.",
    "domainCount": 179
  },
  {
    "id": "webemail",
    "label": "Email",
    "description": "Webmail and internet email services.",
    "domainCount": 340
  },
  {
    "id": "blog",
    "label": "Blog",
    "description": "Blog hosting and publishing sites.",
    "domainCount": 1421
  },
  {
    "id": "streaming",
    "label": "Streaming",
    "description": "Audio and video streaming sites.",
    "domainCount": 3352
  }
];
