// Generated by scripts/generate-site-catalog.ts from packages/shared/src/sites. Do not edit.
export const SITE_CATALOG = {
  "reddit": {
    "id": "reddit",
    "label": "Reddit",
    "hosts": [
      "reddit.com",
      "redd.it"
    ],
    "appHosts": [
      "reddit.com",
      "www.reddit.com",
      "old.reddit.com",
      "new.reddit.com",
      "np.reddit.com",
      "sh.reddit.com",
      "chat.reddit.com",
      "redd.it"
    ],
    "networkDomains": [
      "redditstatic.com",
      "redditmedia.com"
    ],
    "features": [
      {
        "id": "content",
        "label": "Posts you open directly",
        "default": "allow"
      },
      {
        "id": "comments",
        "label": "Comments",
        "default": "allow"
      },
      {
        "id": "search",
        "label": "Search",
        "default": "allow"
      },
      {
        "id": "messages",
        "label": "Messages & chat",
        "default": "allow"
      },
      {
        "id": "notifications",
        "label": "Notifications",
        "default": "allow"
      },
      {
        "id": "compose",
        "label": "Posting",
        "default": "allow"
      },
      {
        "id": "feed",
        "label": "Feeds & subreddit listings",
        "default": "block"
      },
      {
        "id": "recommendations",
        "label": "Recommendations & related posts",
        "default": "block"
      },
      {
        "id": "profiles",
        "label": "User profiles",
        "default": "block"
      },
      {
        "id": "essentials",
        "label": "Sign-in & settings",
        "default": "allow",
        "locked": true
      }
    ],
    "routes": [
      {
        "feature": "content",
        "host": "redd.it",
        "path": "^/([a-z0-9]+)$",
        "item": 1
      },
      {
        "feature": "messages",
        "host": "chat.reddit.com"
      },
      {
        "feature": "content",
        "path": "^/(?:r/[^/]+/)?comments/([a-z0-9]+)(?:/.*)?$",
        "item": 1,
        "judge": {
          "contentSelector": "shreddit-post"
        }
      },
      {
        "feature": "content",
        "path": "^/gallery/([a-z0-9]+)$",
        "item": 1
      },
      {
        "feature": "content",
        "path": "^/r/[^/]+/s/([a-z0-9]+)$",
        "item": 1
      },
      {
        "feature": "search",
        "path": "^/(?:r/[^/]+/)?search$",
        "query": {
          "q": "^[^&#]+$"
        }
      },
      {
        "feature": "messages",
        "path": "^/(?:message|chat)(?:/.*)?$"
      },
      {
        "feature": "notifications",
        "path": "^/notifications$"
      },
      {
        "feature": "compose",
        "path": "^/(?:r/[^/]+/)?submit$"
      },
      {
        "feature": "profiles",
        "path": "^/(?:u|user)/[^/]+(?:/.*)?$"
      },
      {
        "feature": "essentials",
        "path": "^/(?:login|register|password|account|settings|prefs)(?:/.*)?$"
      }
    ],
    "fallbackFeature": "feed",
    "hops": {
      "feature": "recommendations"
    },
    "elements": [
      {
        "feature": "feed",
        "selector": "reddit-sidebar-nav"
      },
      {
        "feature": "feed",
        "selector": "shreddit-feed",
        "on": [
          "content"
        ]
      },
      {
        "feature": "recommendations",
        "selector": "[data-testid*=\"recommend\"], [data-testid*=\"related\"], [data-testid*=\"trending\"]"
      },
      {
        "feature": "recommendations",
        "selector": "aside",
        "on": [
          "content"
        ]
      },
      {
        "feature": "comments",
        "selector": "shreddit-comment-tree, #comment-tree"
      }
    ],
    "entryPoints": [
      {
        "feature": "search",
        "label": "Search Reddit",
        "url": "https://www.reddit.com/search/",
        "param": "q"
      },
      {
        "feature": "messages",
        "label": "Messages",
        "url": "https://www.reddit.com/message/inbox"
      }
    ]
  },
  "hackernews": {
    "id": "hackernews",
    "label": "Hacker News",
    "hosts": [
      "news.ycombinator.com"
    ],
    "appHosts": [
      "news.ycombinator.com"
    ],
    "networkDomains": [],
    "features": [
      {
        "id": "content",
        "label": "Stories you open directly",
        "default": "allow"
      },
      {
        "id": "compose",
        "label": "Submitting & replying",
        "default": "allow"
      },
      {
        "id": "feed",
        "label": "Front page & listings",
        "default": "block"
      },
      {
        "id": "profiles",
        "label": "User profiles",
        "default": "block"
      },
      {
        "id": "essentials",
        "label": "Sign-in & voting",
        "default": "allow",
        "locked": true
      }
    ],
    "routes": [
      {
        "feature": "content",
        "path": "^/item$",
        "query": {
          "id": "^[0-9]+$"
        },
        "item": "id",
        "judge": {
          "contentSelector": ".fatitem"
        }
      },
      {
        "feature": "compose",
        "path": "^/(?:submit|reply|comment|edit)$"
      },
      {
        "feature": "profiles",
        "path": "^/(?:user|submitted|threads|favorites)$"
      },
      {
        "feature": "essentials",
        "path": "^/(?:login|logout|vote|changepw|forgot|x)$"
      }
    ],
    "fallbackFeature": "feed",
    "hops": {
      "feature": "feed"
    },
    "elements": [
      {
        "feature": "feed",
        "selector": "#hnmain > tbody > tr:first-child, .pagetop, .morelink"
      }
    ],
    "entryPoints": []
  },
  "x": {
    "id": "x",
    "label": "X",
    "hosts": [
      "x.com",
      "twitter.com"
    ],
    "appHosts": [
      "x.com",
      "www.x.com",
      "mobile.x.com",
      "twitter.com",
      "www.twitter.com",
      "mobile.twitter.com"
    ],
    "networkDomains": [
      "twimg.com"
    ],
    "features": [
      {
        "id": "content",
        "label": "Posts you open directly",
        "default": "allow"
      },
      {
        "id": "search",
        "label": "Search",
        "default": "allow"
      },
      {
        "id": "messages",
        "label": "Messages",
        "default": "allow"
      },
      {
        "id": "notifications",
        "label": "Notifications",
        "default": "allow"
      },
      {
        "id": "compose",
        "label": "Posting",
        "default": "allow"
      },
      {
        "id": "feed",
        "label": "Home timeline & Explore",
        "default": "block"
      },
      {
        "id": "recommendations",
        "label": "Trends & who to follow",
        "default": "block"
      },
      {
        "id": "profiles",
        "label": "Profiles",
        "default": "block"
      },
      {
        "id": "essentials",
        "label": "Sign-in & settings",
        "default": "allow",
        "locked": true
      }
    ],
    "routes": [
      {
        "feature": "content",
        "path": "^/(?:i/)?(?:[^/]+/)?status/([0-9]+)(?:/.*)?$",
        "item": 1,
        "judge": {
          "contentSelector": "article[data-testid=\"tweet\"]"
        }
      },
      {
        "feature": "search",
        "path": "^/search$",
        "query": {
          "q": "^[^&#]+$"
        }
      },
      {
        "feature": "messages",
        "path": "^/(?:messages|i/chat)(?:/.*)?$"
      },
      {
        "feature": "notifications",
        "path": "^/(?:i/)?notifications(?:/.*)?$"
      },
      {
        "feature": "compose",
        "path": "^/compose/post$"
      },
      {
        "feature": "essentials",
        "path": "^/(?:i/flow/[^/]+|settings(?:/.*)?|login|logout)$"
      },
      {
        "feature": "feed",
        "path": "^/(?:home|explore|search|i/.*)(?:/.*)?$"
      },
      {
        "feature": "profiles",
        "path": "^/[a-z0-9_]{1,15}(?:/(?:with_replies|media|likes|highlights|articles|followers|following))?$"
      }
    ],
    "fallbackFeature": "feed",
    "hops": {
      "feature": "recommendations"
    },
    "elements": [
      {
        "feature": "recommendations",
        "selector": "[data-testid=\"sidebarColumn\"], [data-testid=\"trend\"]"
      },
      {
        "feature": "recommendations",
        "selector": "[data-testid=\"UserCell\"]",
        "on": [
          "content"
        ]
      },
      {
        "feature": "feed",
        "selector": "[data-testid=\"primaryColumn\"] article",
        "on": [
          "compose"
        ]
      }
    ],
    "entryPoints": [
      {
        "feature": "search",
        "label": "Search X",
        "url": "https://x.com/search",
        "param": "q"
      },
      {
        "feature": "compose",
        "label": "Post",
        "url": "https://x.com/compose/post"
      },
      {
        "feature": "notifications",
        "label": "Notifications",
        "url": "https://x.com/notifications"
      },
      {
        "feature": "messages",
        "label": "Messages",
        "url": "https://x.com/messages"
      }
    ]
  },
  "linkedin": {
    "id": "linkedin",
    "label": "LinkedIn",
    "hosts": [
      "linkedin.com"
    ],
    "appHosts": [
      "linkedin.com",
      "www.linkedin.com",
      "m.linkedin.com"
    ],
    "networkDomains": [
      "licdn.com"
    ],
    "features": [
      {
        "id": "content",
        "label": "Posts & articles you open directly",
        "default": "allow"
      },
      {
        "id": "search",
        "label": "Search",
        "default": "allow"
      },
      {
        "id": "messages",
        "label": "Messaging",
        "default": "allow"
      },
      {
        "id": "notifications",
        "label": "Notifications",
        "default": "allow"
      },
      {
        "id": "compose",
        "label": "Posting",
        "default": "allow"
      },
      {
        "id": "feed",
        "label": "Feed",
        "default": "block"
      },
      {
        "id": "recommendations",
        "label": "Recommendations",
        "default": "block"
      },
      {
        "id": "profiles",
        "label": "Profiles",
        "default": "block"
      },
      {
        "id": "jobs",
        "label": "Jobs",
        "default": "block"
      },
      {
        "id": "essentials",
        "label": "Sign-in & settings",
        "default": "allow",
        "locked": true
      }
    ],
    "routes": [
      {
        "feature": "content",
        "path": "^/feed/update/urn:li:(?:activity|share|ugcpost):([0-9]+)(?:/.*)?$",
        "item": 1,
        "judge": {
          "contentSelector": ".feed-shared-update-v2"
        }
      },
      {
        "feature": "content",
        "path": "^/(?:posts|pulse)/([^/]+)$",
        "item": 1,
        "judge": {
          "contentSelector": "article, main"
        }
      },
      {
        "feature": "search",
        "path": "^/search/results/[^/]+$",
        "query": {
          "keywords": "^[^&#]+$"
        }
      },
      {
        "feature": "messages",
        "path": "^/messaging(?:/.*)?$"
      },
      {
        "feature": "notifications",
        "path": "^/notifications(?:/.*)?$"
      },
      {
        "feature": "compose",
        "path": "^/(?:post/new|content-management)(?:/.*)?$"
      },
      {
        "feature": "feed",
        "path": "^/feed$",
        "shell": true
      },
      {
        "feature": "profiles",
        "path": "^/(?:in|company|school)/[^/]+(?:/.*)?$"
      },
      {
        "feature": "jobs",
        "path": "^/jobs(?:/.*)?$"
      },
      {
        "feature": "essentials",
        "path": "^/(?:login|signup|checkpoint|uas|authwall|psettings|mypreferences)(?:/.*)?$"
      }
    ],
    "fallbackFeature": "feed",
    "hops": {
      "feature": "recommendations"
    },
    "elements": [
      {
        "feature": "recommendations",
        "selector": ".scaffold-layout__aside, .right-rail"
      },
      {
        "feature": "feed",
        "selector": ".feed-shared-update-v2, [data-urn^=\"urn:li:activity:\"], [data-urn^=\"urn:li:share:\"]",
        "on": [
          "feed"
        ]
      }
    ],
    "entryPoints": [
      {
        "feature": "search",
        "label": "Search LinkedIn posts",
        "url": "https://www.linkedin.com/search/results/content/",
        "param": "keywords"
      },
      {
        "feature": "compose",
        "label": "Post",
        "url": "https://www.linkedin.com/feed/"
      },
      {
        "feature": "notifications",
        "label": "Notifications",
        "url": "https://www.linkedin.com/notifications/"
      },
      {
        "feature": "messages",
        "label": "Messages",
        "url": "https://www.linkedin.com/messaging/"
      }
    ]
  },
  "instagram": {
    "id": "instagram",
    "label": "Instagram",
    "hosts": [
      "instagram.com"
    ],
    "appHosts": [
      "instagram.com",
      "www.instagram.com"
    ],
    "networkDomains": [
      "cdninstagram.com",
      "fbcdn.net"
    ],
    "features": [
      {
        "id": "content",
        "label": "Posts & reels you open directly",
        "default": "allow"
      },
      {
        "id": "search",
        "label": "Search",
        "default": "allow"
      },
      {
        "id": "messages",
        "label": "Direct messages",
        "default": "allow"
      },
      {
        "id": "compose",
        "label": "Posting",
        "default": "allow"
      },
      {
        "id": "feed",
        "label": "Home feed",
        "default": "block"
      },
      {
        "id": "explore",
        "label": "Explore & Reels tab",
        "default": "block"
      },
      {
        "id": "stories",
        "label": "Stories",
        "default": "block"
      },
      {
        "id": "recommendations",
        "label": "Suggestions & swiping",
        "default": "block"
      },
      {
        "id": "profiles",
        "label": "Profiles",
        "default": "block"
      },
      {
        "id": "essentials",
        "label": "Sign-in & settings",
        "default": "allow",
        "locked": true
      }
    ],
    "routes": [
      {
        "feature": "content",
        "path": "^/(?:[^/]+/)?(?:p|reel|reels|tv)/([-_a-z0-9]+)$",
        "item": 1,
        "judge": {
          "contentSelector": "article, main"
        }
      },
      {
        "feature": "search",
        "path": "^/explore/search$",
        "query": {
          "q": "^[^&#]+$"
        }
      },
      {
        "feature": "messages",
        "path": "^/direct(?:/.*)?$"
      },
      {
        "feature": "compose",
        "path": "^/create(?:/.*)?$"
      },
      {
        "feature": "feed",
        "path": "^/$",
        "shell": true
      },
      {
        "feature": "explore",
        "path": "^/(?:explore|reels)(?:/.*)?$"
      },
      {
        "feature": "stories",
        "path": "^/stories(?:/.*)?$"
      },
      {
        "feature": "essentials",
        "path": "^/(?:accounts|challenge|emails|session)(?:/.*)?$"
      },
      {
        "feature": "profiles",
        "path": "^/[-_.a-z0-9]+(?:/(?:tagged|reels|saved))?$"
      }
    ],
    "fallbackFeature": "feed",
    "hops": {
      "feature": "recommendations"
    },
    "elements": [
      {
        "feature": "feed",
        "selector": "main",
        "on": [
          "feed"
        ]
      }
    ],
    "entryPoints": [
      {
        "feature": "search",
        "label": "Search Instagram",
        "url": "https://www.instagram.com/explore/search/",
        "param": "q"
      },
      {
        "feature": "compose",
        "label": "Create or notifications",
        "url": "https://www.instagram.com/"
      },
      {
        "feature": "messages",
        "label": "Messages",
        "url": "https://www.instagram.com/direct/inbox/"
      }
    ]
  },
  "youtube": {
    "id": "youtube",
    "label": "YouTube",
    "hosts": [
      "youtube.com",
      "youtu.be"
    ],
    "appHosts": [
      "youtube.com",
      "www.youtube.com",
      "m.youtube.com",
      "studio.youtube.com",
      "youtu.be"
    ],
    "networkDomains": [
      "ytimg.com",
      "googlevideo.com",
      "ggpht.com"
    ],
    "features": [
      {
        "id": "content",
        "label": "Videos you open directly",
        "default": "allow"
      },
      {
        "id": "shorts",
        "label": "Shorts you open directly",
        "default": "allow"
      },
      {
        "id": "comments",
        "label": "Comments",
        "default": "allow"
      },
      {
        "id": "search",
        "label": "Search",
        "default": "allow"
      },
      {
        "id": "notifications",
        "label": "Notifications",
        "default": "allow"
      },
      {
        "id": "studio",
        "label": "YouTube Studio & uploads",
        "default": "allow"
      },
      {
        "id": "feed",
        "label": "Home, subscriptions & trending",
        "default": "block"
      },
      {
        "id": "recommendations",
        "label": "Recommended & up next",
        "default": "block"
      },
      {
        "id": "channels",
        "label": "Channel pages",
        "default": "block"
      },
      {
        "id": "essentials",
        "label": "Sign-in & account",
        "default": "allow",
        "locked": true
      }
    ],
    "routes": [
      {
        "feature": "studio",
        "host": "studio.youtube.com"
      },
      {
        "feature": "content",
        "host": "youtu.be",
        "path": "^/([-_a-z0-9]{11})$",
        "item": 1
      },
      {
        "feature": "content",
        "path": "^/watch$",
        "query": {
          "v": "^[-_a-zA-Z0-9]{11}$"
        },
        "item": "v",
        "judge": {
          "contentSelector": "ytd-watch-metadata, #above-the-fold"
        }
      },
      {
        "feature": "content",
        "path": "^/live/([-_a-z0-9]{11})$",
        "item": 1
      },
      {
        "feature": "shorts",
        "path": "^/shorts/([-_a-z0-9]{11})$",
        "item": 1
      },
      {
        "feature": "search",
        "path": "^/results$",
        "query": {
          "search_query": "^[^&#]+$"
        }
      },
      {
        "feature": "notifications",
        "path": "^/feed/notifications$"
      },
      {
        "feature": "studio",
        "path": "^/upload$"
      },
      {
        "feature": "essentials",
        "path": "^/(?:account(?:_[^/]+)?|signin|logout|premium|paid_memberships)(?:/.*)?$"
      },
      {
        "feature": "channels",
        "path": "^/(?:@[^/]+|channel/[^/]+|c/[^/]+|user/[^/]+)(?:/.*)?$"
      }
    ],
    "fallbackFeature": "feed",
    "hops": {
      "feature": "recommendations"
    },
    "elements": [
      {
        "feature": "recommendations",
        "selector": "#secondary, #related, ytd-watch-next-secondary-results-renderer, .ytp-endscreen-content, .ytp-ce-element, ytd-compact-video-renderer, ytd-reel-shelf-renderer, ytd-rich-shelf-renderer",
        "on": [
          "content",
          "shorts"
        ]
      },
      {
        "feature": "comments",
        "selector": "ytd-comments#comments"
      }
    ],
    "entryPoints": [
      {
        "feature": "search",
        "label": "Search YouTube",
        "url": "https://www.youtube.com/results",
        "param": "search_query"
      },
      {
        "feature": "studio",
        "label": "Studio",
        "url": "https://studio.youtube.com/"
      }
    ]
  }
};
