// Generated by scripts/generate-site-catalog.ts from packages/shared/src/sites. Do not edit.
export const SITE_CATALOG = {
  "reddit": {
    "id": "reddit",
    "label": "Reddit",
    "hosts": [
      "reddit.com",
      "redd.it"
    ],
    "appHosts": [
      "reddit.com",
      "www.reddit.com",
      "old.reddit.com",
      "new.reddit.com",
      "np.reddit.com",
      "sh.reddit.com",
      "chat.reddit.com",
      "redd.it"
    ],
    "networkDomains": [
      "redditstatic.com",
      "redditmedia.com"
    ],
    "features": [
      {
        "id": "content",
        "label": "Posts you open directly",
        "default": "allow"
      },
      {
        "id": "comments",
        "label": "Comments",
        "default": "allow"
      },
      {
        "id": "search",
        "label": "Search",
        "default": "allow"
      },
      {
        "id": "messages",
        "label": "Messages & chat",
        "default": "allow"
      },
      {
        "id": "notifications",
        "label": "Notifications",
        "default": "allow"
      },
      {
        "id": "compose",
        "label": "Posting",
        "default": "allow"
      },
      {
        "id": "feed",
        "label": "Feeds & subreddit listings",
        "default": "block"
      },
      {
        "id": "recommendations",
        "label": "Recommendations & related posts",
        "default": "block"
      },
      {
        "id": "profiles",
        "label": "User profiles",
        "default": "block"
      },
      {
        "id": "essentials",
        "label": "Sign-in & settings",
        "default": "allow",
        "locked": true
      }
    ],
    "routes": [
      {
        "feature": "content",
        "host": "redd.it",
        "path": "^/([a-z0-9]+)$"
      },
      {
        "feature": "messages",
        "host": "chat.reddit.com"
      },
      {
        "feature": "content",
        "path": "^/(?:r/[^/]+/)?comments/([a-z0-9]+)(?:/.*)?$",
        "judge": {
          "contentSelector": "shreddit-post"
        }
      },
      {
        "feature": "content",
        "path": "^/gallery/([a-z0-9]+)$"
      },
      {
        "feature": "content",
        "path": "^/r/[^/]+/s/([a-z0-9]+)$"
      },
      {
        "feature": "search",
        "path": "^/(?:r/[^/]+/)?search$",
        "query": {
          "q": "^[^&#]+$"
        }
      },
      {
        "feature": "messages",
        "path": "^/(?:message|chat)(?:/.*)?$"
      },
      {
        "feature": "notifications",
        "path": "^/notifications$"
      },
      {
        "feature": "compose",
        "path": "^/(?:r/[^/]+/)?submit$"
      },
      {
        "feature": "profiles",
        "path": "^/(?:u|user)/[^/]+(?:/.*)?$"
      },
      {
        "feature": "essentials",
        "path": "^/(?:login|register|password|account|settings|prefs)(?:/.*)?$"
      }
    ],
    "fallbackFeature": "feed",
    "elements": [
      {
        "feature": "feed",
        "selector": "shreddit-feed, shreddit-gallery-carousel, #siteTable",
        "on": [
          "feed"
        ]
      },
      {
        "feature": "recommendations",
        "selector": "[data-testid*=\"recommend\"], [data-testid*=\"related\"], [data-testid*=\"trending\"], #right-sidebar-container, .trending-subreddits"
      },
      {
        "feature": "recommendations",
        "selector": "aside, shreddit-feed",
        "on": [
          "content"
        ]
      },
      {
        "feature": "comments",
        "selector": "shreddit-comment-tree, #comment-tree, .commentarea"
      },
      {
        "feature": "content",
        "selector": "main, .content[role=\"main\"]",
        "on": [
          "content"
        ]
      },
      {
        "feature": "search",
        "selector": "main, .content[role=\"main\"]",
        "on": [
          "search"
        ]
      },
      {
        "feature": "messages",
        "selector": "main, .content[role=\"main\"]",
        "on": [
          "messages"
        ]
      },
      {
        "feature": "notifications",
        "selector": "main, .content[role=\"main\"]",
        "on": [
          "notifications"
        ]
      },
      {
        "feature": "compose",
        "selector": "main, .content[role=\"main\"]",
        "on": [
          "compose"
        ]
      },
      {
        "feature": "profiles",
        "selector": "main, .content[role=\"main\"]",
        "on": [
          "profiles"
        ]
      }
    ]
  },
  "hackernews": {
    "id": "hackernews",
    "label": "Hacker News",
    "hosts": [
      "news.ycombinator.com"
    ],
    "appHosts": [
      "news.ycombinator.com"
    ],
    "networkDomains": [],
    "features": [
      {
        "id": "content",
        "label": "Stories you open directly",
        "default": "allow"
      },
      {
        "id": "compose",
        "label": "Submitting & replying",
        "default": "allow"
      },
      {
        "id": "feed",
        "label": "Front page & listings",
        "default": "block"
      },
      {
        "id": "profiles",
        "label": "User profiles",
        "default": "block"
      },
      {
        "id": "essentials",
        "label": "Sign-in & voting",
        "default": "allow",
        "locked": true
      }
    ],
    "routes": [
      {
        "feature": "content",
        "path": "^/item$",
        "query": {
          "id": "^[0-9]+$"
        },
        "judge": {
          "contentSelector": ".fatitem"
        }
      },
      {
        "feature": "compose",
        "path": "^/(?:submit|reply|comment|edit)$"
      },
      {
        "feature": "profiles",
        "path": "^/(?:user|submitted|threads|favorites)$"
      },
      {
        "feature": "essentials",
        "path": "^/(?:login|logout|vote|changepw|forgot|x)$"
      }
    ],
    "fallbackFeature": "feed",
    "elements": [
      {
        "feature": "feed",
        "selector": "#bigbox",
        "on": [
          "feed"
        ]
      },
      {
        "feature": "content",
        "selector": "#bigbox",
        "on": [
          "content"
        ]
      },
      {
        "feature": "compose",
        "selector": "#bigbox",
        "on": [
          "compose"
        ]
      },
      {
        "feature": "profiles",
        "selector": "#bigbox",
        "on": [
          "profiles"
        ]
      }
    ]
  },
  "x": {
    "id": "x",
    "label": "X",
    "hosts": [
      "x.com",
      "twitter.com"
    ],
    "appHosts": [
      "x.com",
      "www.x.com",
      "mobile.x.com",
      "twitter.com",
      "www.twitter.com",
      "mobile.twitter.com"
    ],
    "networkDomains": [
      "twimg.com"
    ],
    "features": [
      {
        "id": "content",
        "label": "Posts you open directly",
        "default": "allow"
      },
      {
        "id": "search",
        "label": "Search",
        "default": "allow"
      },
      {
        "id": "messages",
        "label": "Messages",
        "default": "allow"
      },
      {
        "id": "notifications",
        "label": "Notifications",
        "default": "allow"
      },
      {
        "id": "compose",
        "label": "Posting",
        "default": "allow"
      },
      {
        "id": "feed",
        "label": "Home timeline & Explore",
        "default": "block"
      },
      {
        "id": "recommendations",
        "label": "Trends & who to follow",
        "default": "block"
      },
      {
        "id": "profiles",
        "label": "Profiles",
        "default": "block"
      },
      {
        "id": "essentials",
        "label": "Sign-in & settings",
        "default": "allow",
        "locked": true
      }
    ],
    "routes": [
      {
        "feature": "content",
        "path": "^/(?:i/)?(?:[^/]+/)?status/([0-9]+)(?:/.*)?$",
        "judge": {
          "contentSelector": "article[data-testid=\"tweet\"]"
        }
      },
      {
        "feature": "search",
        "path": "^/search$",
        "query": {
          "q": "^[^&#]+$"
        }
      },
      {
        "feature": "messages",
        "path": "^/(?:messages|i/chat)(?:/.*)?$"
      },
      {
        "feature": "notifications",
        "path": "^/(?:i/)?notifications(?:/.*)?$"
      },
      {
        "feature": "compose",
        "path": "^/compose/post$"
      },
      {
        "feature": "essentials",
        "path": "^/(?:i/flow/[^/]+|settings(?:/.*)?|login|logout)$"
      },
      {
        "feature": "feed",
        "path": "^/(?:home|explore|search|i/.*)(?:/.*)?$"
      },
      {
        "feature": "profiles",
        "path": "^/[a-z0-9_]{1,15}(?:/(?:with_replies|media|likes|highlights|articles|followers|following))?$"
      }
    ],
    "fallbackFeature": "feed",
    "elements": [
      {
        "feature": "feed",
        "selector": "[data-testid=\"primaryColumn\"] section[role=\"region\"]",
        "on": [
          "feed",
          "compose"
        ]
      },
      {
        "feature": "recommendations",
        "selector": "[data-testid=\"sidebarColumn\"] :is(section, aside), [data-testid=\"trend\"]"
      },
      {
        "feature": "recommendations",
        "selector": "[data-testid=\"UserCell\"], [data-testid=\"cellInnerDiv\"]:has(h2), [data-testid=\"cellInnerDiv\"]:has(h2) ~ [data-testid=\"cellInnerDiv\"]",
        "on": [
          "content"
        ]
      },
      {
        "feature": "content",
        "selector": "[data-testid=\"primaryColumn\"] section[role=\"region\"]",
        "on": [
          "content"
        ]
      },
      {
        "feature": "search",
        "selector": "[data-testid=\"primaryColumn\"] section[role=\"region\"]",
        "on": [
          "search"
        ]
      },
      {
        "feature": "profiles",
        "selector": "[data-testid=\"primaryColumn\"] section[role=\"region\"]",
        "on": [
          "profiles"
        ]
      },
      {
        "feature": "notifications",
        "selector": "[data-testid=\"primaryColumn\"]",
        "on": [
          "notifications"
        ]
      },
      {
        "feature": "messages",
        "selector": "main[role=\"main\"]",
        "on": [
          "messages"
        ]
      },
      {
        "feature": "compose",
        "selector": "[data-testid=\"SideNav_NewTweet_Button\"], [data-testid=\"tweetButtonInline\"]"
      },
      {
        "feature": "compose",
        "selector": "[role=\"dialog\"]",
        "on": [
          "compose"
        ]
      }
    ]
  },
  "linkedin": {
    "id": "linkedin",
    "label": "LinkedIn",
    "hosts": [
      "linkedin.com"
    ],
    "appHosts": [
      "linkedin.com",
      "www.linkedin.com",
      "m.linkedin.com"
    ],
    "networkDomains": [
      "licdn.com"
    ],
    "features": [
      {
        "id": "content",
        "label": "Posts & articles you open directly",
        "default": "allow"
      },
      {
        "id": "search",
        "label": "Search",
        "default": "allow"
      },
      {
        "id": "messages",
        "label": "Messaging",
        "default": "allow"
      },
      {
        "id": "notifications",
        "label": "Notifications",
        "default": "allow"
      },
      {
        "id": "compose",
        "label": "Posting",
        "default": "allow"
      },
      {
        "id": "feed",
        "label": "Feed",
        "default": "block"
      },
      {
        "id": "recommendations",
        "label": "Recommendations",
        "default": "block"
      },
      {
        "id": "profiles",
        "label": "Profiles",
        "default": "block"
      },
      {
        "id": "jobs",
        "label": "Jobs",
        "default": "block"
      },
      {
        "id": "essentials",
        "label": "Sign-in & settings",
        "default": "allow",
        "locked": true
      }
    ],
    "routes": [
      {
        "feature": "content",
        "path": "^/feed/update/urn:li:(?:activity|share|ugcpost):([0-9]+)(?:/.*)?$",
        "judge": {
          "contentSelector": ".feed-shared-update-v2"
        }
      },
      {
        "feature": "content",
        "path": "^/(?:posts|pulse)/([^/]+)$",
        "judge": {
          "contentSelector": "article, main"
        }
      },
      {
        "feature": "search",
        "path": "^/search/results/[^/]+$",
        "query": {
          "keywords": "^[^&#]+$"
        }
      },
      {
        "feature": "messages",
        "path": "^/messaging(?:/.*)?$"
      },
      {
        "feature": "notifications",
        "path": "^/notifications(?:/.*)?$"
      },
      {
        "feature": "compose",
        "path": "^/(?:post/new|content-management)(?:/.*)?$"
      },
      {
        "feature": "feed",
        "path": "^/feed$"
      },
      {
        "feature": "recommendations",
        "path": "^/mynetwork(?:/.*)?$"
      },
      {
        "feature": "profiles",
        "path": "^/(?:in|company|school)/[^/]+(?:/.*)?$"
      },
      {
        "feature": "jobs",
        "path": "^/jobs(?:/.*)?$"
      },
      {
        "feature": "essentials",
        "path": "^/(?:login|signup|checkpoint|uas|authwall|psettings|mypreferences)(?:/.*)?$"
      }
    ],
    "fallbackFeature": "feed",
    "elements": [
      {
        "feature": "feed",
        "selector": ".feed-shared-update-v2, [data-urn^=\"urn:li:activity:\"], [data-urn^=\"urn:li:share:\"], .scaffold-finite-scroll",
        "on": [
          "feed"
        ]
      },
      {
        "feature": "recommendations",
        "selector": ".scaffold-layout__aside, .right-rail, #feed-news-module"
      },
      {
        "feature": "recommendations",
        "selector": "main",
        "on": [
          "recommendations"
        ]
      },
      {
        "feature": "messages",
        "selector": "#msg-overlay, .msg-overlay-container"
      },
      {
        "feature": "compose",
        "selector": ".share-box-feed-entry__closed-share-box"
      },
      {
        "feature": "content",
        "selector": "main",
        "on": [
          "content"
        ]
      },
      {
        "feature": "search",
        "selector": "main",
        "on": [
          "search"
        ]
      },
      {
        "feature": "messages",
        "selector": "main",
        "on": [
          "messages"
        ]
      },
      {
        "feature": "notifications",
        "selector": "main",
        "on": [
          "notifications"
        ]
      },
      {
        "feature": "compose",
        "selector": "main",
        "on": [
          "compose"
        ]
      },
      {
        "feature": "profiles",
        "selector": "main",
        "on": [
          "profiles"
        ]
      },
      {
        "feature": "jobs",
        "selector": "main",
        "on": [
          "jobs"
        ]
      }
    ]
  },
  "instagram": {
    "id": "instagram",
    "label": "Instagram",
    "hosts": [
      "instagram.com"
    ],
    "appHosts": [
      "instagram.com",
      "www.instagram.com"
    ],
    "networkDomains": [
      "cdninstagram.com",
      "fbcdn.net"
    ],
    "features": [
      {
        "id": "content",
        "label": "Posts & reels you open directly",
        "default": "allow"
      },
      {
        "id": "search",
        "label": "Search",
        "default": "allow"
      },
      {
        "id": "messages",
        "label": "Direct messages",
        "default": "allow"
      },
      {
        "id": "compose",
        "label": "Posting",
        "default": "allow"
      },
      {
        "id": "feed",
        "label": "Home feed",
        "default": "block"
      },
      {
        "id": "explore",
        "label": "Explore & Reels tab",
        "default": "block"
      },
      {
        "id": "stories",
        "label": "Stories",
        "default": "block"
      },
      {
        "id": "recommendations",
        "label": "Suggestions",
        "default": "block"
      },
      {
        "id": "profiles",
        "label": "Profiles",
        "default": "block"
      },
      {
        "id": "essentials",
        "label": "Sign-in & settings",
        "default": "allow",
        "locked": true
      }
    ],
    "routes": [
      {
        "feature": "content",
        "path": "^/(?:[^/]+/)?(?:p|reel|reels|tv)/([-_a-z0-9]+)$",
        "judge": {
          "contentSelector": "article, main"
        }
      },
      {
        "feature": "search",
        "path": "^/explore/search$",
        "query": {
          "q": "^[^&#]+$"
        }
      },
      {
        "feature": "messages",
        "path": "^/direct(?:/.*)?$"
      },
      {
        "feature": "compose",
        "path": "^/create(?:/.*)?$"
      },
      {
        "feature": "feed",
        "path": "^/$"
      },
      {
        "feature": "explore",
        "path": "^/(?:explore|reels)(?:/.*)?$"
      },
      {
        "feature": "stories",
        "path": "^/stories(?:/.*)?$"
      },
      {
        "feature": "essentials",
        "path": "^/(?:accounts|challenge|emails|session)(?:/.*)?$"
      },
      {
        "feature": "profiles",
        "path": "^/[-_.a-z0-9]+(?:/(?:tagged|reels|saved))?$"
      }
    ],
    "fallbackFeature": "feed",
    "elements": [
      {
        "feature": "feed",
        "selector": "main",
        "on": [
          "feed"
        ]
      },
      {
        "feature": "explore",
        "selector": "main",
        "on": [
          "explore"
        ]
      },
      {
        "feature": "stories",
        "selector": "main, section",
        "on": [
          "stories"
        ]
      },
      {
        "feature": "stories",
        "selector": "main [role=\"menu\"]:has(canvas)"
      },
      {
        "feature": "recommendations",
        "selector": "main div:has(> a[href^=\"/explore/people\"])"
      },
      {
        "feature": "recommendations",
        "selector": "main article ~ div",
        "on": [
          "content"
        ]
      },
      {
        "feature": "content",
        "selector": "main, article",
        "on": [
          "content"
        ]
      },
      {
        "feature": "search",
        "selector": "main",
        "on": [
          "search"
        ]
      },
      {
        "feature": "messages",
        "selector": "main, [role=\"main\"]",
        "on": [
          "messages"
        ]
      },
      {
        "feature": "compose",
        "selector": "[role=\"dialog\"]",
        "on": [
          "compose"
        ]
      },
      {
        "feature": "profiles",
        "selector": "main",
        "on": [
          "profiles"
        ]
      }
    ]
  },
  "youtube": {
    "id": "youtube",
    "label": "YouTube",
    "hosts": [
      "youtube.com",
      "youtu.be"
    ],
    "appHosts": [
      "youtube.com",
      "www.youtube.com",
      "m.youtube.com",
      "studio.youtube.com",
      "youtu.be"
    ],
    "networkDomains": [
      "ytimg.com",
      "googlevideo.com",
      "ggpht.com"
    ],
    "features": [
      {
        "id": "content",
        "label": "Videos you open directly",
        "default": "allow"
      },
      {
        "id": "shorts",
        "label": "Shorts you open directly",
        "default": "allow"
      },
      {
        "id": "comments",
        "label": "Comments",
        "default": "allow"
      },
      {
        "id": "search",
        "label": "Search",
        "default": "allow"
      },
      {
        "id": "notifications",
        "label": "Notifications",
        "default": "allow"
      },
      {
        "id": "studio",
        "label": "YouTube Studio & uploads",
        "default": "allow"
      },
      {
        "id": "feed",
        "label": "Home, subscriptions & trending",
        "default": "block"
      },
      {
        "id": "recommendations",
        "label": "Recommended & up next",
        "default": "block"
      },
      {
        "id": "channels",
        "label": "Channel pages",
        "default": "block"
      },
      {
        "id": "essentials",
        "label": "Sign-in & account",
        "default": "allow",
        "locked": true
      }
    ],
    "routes": [
      {
        "feature": "studio",
        "host": "studio.youtube.com"
      },
      {
        "feature": "content",
        "host": "youtu.be",
        "path": "^/([-_a-z0-9]{11})$"
      },
      {
        "feature": "content",
        "path": "^/watch$",
        "query": {
          "v": "^[-_a-zA-Z0-9]{11}$"
        },
        "judge": {
          "contentSelector": "ytd-watch-metadata, #above-the-fold"
        }
      },
      {
        "feature": "content",
        "path": "^/live/([-_a-z0-9]{11})$"
      },
      {
        "feature": "shorts",
        "path": "^/shorts/([-_a-z0-9]{11})$"
      },
      {
        "feature": "search",
        "path": "^/results$",
        "query": {
          "search_query": "^[^&#]+$"
        }
      },
      {
        "feature": "notifications",
        "path": "^/feed/notifications$"
      },
      {
        "feature": "studio",
        "path": "^/upload$"
      },
      {
        "feature": "essentials",
        "path": "^/(?:account(?:_[^/]+)?|signin|logout|premium|paid_memberships)(?:/.*)?$"
      },
      {
        "feature": "channels",
        "path": "^/(?:@[^/]+|channel/[^/]+|c/[^/]+|user/[^/]+)(?:/.*)?$"
      }
    ],
    "fallbackFeature": "feed",
    "elements": [
      {
        "feature": "feed",
        "selector": "ytd-browse, ytm-browse",
        "on": [
          "feed"
        ]
      },
      {
        "feature": "recommendations",
        "selector": "#secondary, #related, ytd-watch-next-secondary-results-renderer, .ytp-endscreen-content, .ytp-ce-element, .ytp-autonav-endscreen-countdown-overlay, ytd-compact-video-renderer, ytd-reel-shelf-renderer, ytd-rich-shelf-renderer, #navigation-button-up, #navigation-button-down",
        "on": [
          "content",
          "shorts"
        ]
      },
      {
        "feature": "recommendations",
        "selector": "ytd-search ytd-shelf-renderer, ytd-search ytd-reel-shelf-renderer, ytd-search ytd-horizontal-card-list-renderer",
        "on": [
          "search"
        ]
      },
      {
        "feature": "comments",
        "selector": "ytd-comments#comments, ytm-comment-section-renderer"
      },
      {
        "feature": "content",
        "selector": "ytd-watch-flexy, ytm-watch",
        "on": [
          "content"
        ]
      },
      {
        "feature": "shorts",
        "selector": "ytd-shorts",
        "on": [
          "shorts"
        ]
      },
      {
        "feature": "shorts",
        "selector": "ytd-reel-shelf-renderer, ytd-rich-shelf-renderer[is-shorts], ytd-guide-entry-renderer:has(a[title=\"Shorts\"]), ytd-mini-guide-entry-renderer[aria-label=\"Shorts\"]"
      },
      {
        "feature": "search",
        "selector": "ytd-search, ytm-search",
        "on": [
          "search"
        ]
      },
      {
        "feature": "notifications",
        "selector": "ytd-notification-topbar-button-renderer"
      },
      {
        "feature": "notifications",
        "selector": "ytd-browse, ytm-browse",
        "on": [
          "notifications"
        ]
      },
      {
        "feature": "studio",
        "selector": "ytcp-app, ytd-browse",
        "on": [
          "studio"
        ]
      },
      {
        "feature": "channels",
        "selector": "ytd-browse, ytm-browse",
        "on": [
          "channels"
        ]
      }
    ]
  },
  "theverge": {
    "id": "theverge",
    "label": "The Verge",
    "hosts": [
      "theverge.com"
    ],
    "appHosts": [
      "theverge.com",
      "www.theverge.com"
    ],
    "networkDomains": [],
    "features": [
      {
        "id": "content",
        "label": "Articles you open directly",
        "default": "allow"
      },
      {
        "id": "search",
        "label": "Search",
        "default": "allow"
      },
      {
        "id": "feed",
        "label": "Homepage & section pages",
        "default": "block"
      },
      {
        "id": "recommendations",
        "label": "Recommended stories",
        "default": "block"
      },
      {
        "id": "profiles",
        "label": "Author pages",
        "default": "block"
      },
      {
        "id": "essentials",
        "label": "Sign-in & account",
        "default": "allow",
        "locked": true
      }
    ],
    "routes": [
      {
        "feature": "content",
        "path": "^/(?:[a-z0-9-]+|[0-9]{4}/[0-9]{1,2}/[0-9]{1,2})/[0-9]+/[^/]+$",
        "judge": {
          "contentSelector": "article"
        }
      },
      {
        "feature": "search",
        "path": "^/search$"
      },
      {
        "feature": "profiles",
        "path": "^/authors/[^/]+$"
      },
      {
        "feature": "essentials",
        "path": "^/(?:account|subscribe|sign-?in|login|logout|newsletters?)(?:/.*)?$"
      }
    ],
    "fallbackFeature": "feed",
    "elements": [
      {
        "feature": "feed",
        "selector": "main",
        "on": [
          "feed"
        ]
      },
      {
        "feature": "recommendations",
        "selector": ".duet--layout--rail, .duet--layout--article-recirc-color-container, .duet--layout--header-pattern, .duet--article--related, .duet--ad--native-ad-linkset",
        "on": [
          "content",
          "search"
        ]
      },
      {
        "feature": "recommendations",
        "selector": ".duet--homepage--most-popular, .duet--homepage--most-discussed"
      },
      {
        "feature": "content",
        "selector": "main",
        "on": [
          "content"
        ]
      },
      {
        "feature": "search",
        "selector": "main",
        "on": [
          "search"
        ]
      },
      {
        "feature": "profiles",
        "selector": "main",
        "on": [
          "profiles"
        ]
      }
    ]
  },
  "theringer": {
    "id": "theringer",
    "label": "The Ringer",
    "hosts": [
      "theringer.com"
    ],
    "appHosts": [
      "theringer.com",
      "www.theringer.com"
    ],
    "networkDomains": [],
    "features": [
      {
        "id": "content",
        "label": "Articles you open directly",
        "default": "allow"
      },
      {
        "id": "episodes",
        "label": "Podcast episodes you open directly",
        "default": "allow"
      },
      {
        "id": "search",
        "label": "Search",
        "default": "allow"
      },
      {
        "id": "feed",
        "label": "Homepage, topics & shows",
        "default": "block"
      },
      {
        "id": "recommendations",
        "label": "Recommended stories",
        "default": "block"
      },
      {
        "id": "essentials",
        "label": "Sign-in & account",
        "default": "allow",
        "locked": true
      }
    ],
    "routes": [
      {
        "feature": "content",
        "path": "^/[0-9]{4}/[0-9]{2}/[0-9]{2}/[^/]+/[^/]+$",
        "judge": {
          "contentSelector": "article"
        }
      },
      {
        "feature": "episodes",
        "path": "^/podcasts/[^/]+/[0-9]{4}/[0-9]{2}/[0-9]{2}/[^/]+$",
        "judge": {
          "contentSelector": "main > section"
        }
      },
      {
        "feature": "search",
        "path": "^/search$"
      },
      {
        "feature": "essentials",
        "path": "^/(?:account|subscribe|sign-?in|login|logout|newsletters?)(?:/.*)?$"
      }
    ],
    "fallbackFeature": "feed",
    "elements": [
      {
        "feature": "feed",
        "selector": "main",
        "on": [
          "feed"
        ]
      },
      {
        "feature": "recommendations",
        "selector": "#the-pulse, [data-module=\"the-pulse\"]"
      },
      {
        "feature": "recommendations",
        "selector": "[data-sentry-component=\"RelatedContent\"], [data-sentry-component=\"ReadMore\"], main > section",
        "on": [
          "content"
        ]
      },
      {
        "feature": "recommendations",
        "selector": "main > section:nth-of-type(n+3)",
        "on": [
          "episodes"
        ]
      },
      {
        "feature": "content",
        "selector": "main",
        "on": [
          "content"
        ]
      },
      {
        "feature": "episodes",
        "selector": "main",
        "on": [
          "episodes"
        ]
      },
      {
        "feature": "search",
        "selector": "main",
        "on": [
          "search"
        ]
      }
    ]
  },
  "substack": {
    "id": "substack",
    "label": "Substack",
    "hosts": [
      "substack.com"
    ],
    "appHosts": [
      "substack.com",
      "www.substack.com"
    ],
    "networkDomains": [
      "substackcdn.com"
    ],
    "features": [
      {
        "id": "content",
        "label": "Posts & notes you open directly",
        "default": "allow"
      },
      {
        "id": "publications",
        "label": "Newsletter sites",
        "default": "allow"
      },
      {
        "id": "inbox",
        "label": "Subscriptions inbox",
        "default": "allow"
      },
      {
        "id": "messages",
        "label": "Chat & messages",
        "default": "allow"
      },
      {
        "id": "notifications",
        "label": "Activity",
        "default": "allow"
      },
      {
        "id": "search",
        "label": "Search",
        "default": "allow"
      },
      {
        "id": "feed",
        "label": "Home, Notes & Explore",
        "default": "block"
      },
      {
        "id": "recommendations",
        "label": "Recommendations",
        "default": "block"
      },
      {
        "id": "profiles",
        "label": "Profiles",
        "default": "block"
      },
      {
        "id": "essentials",
        "label": "Sign-in & account",
        "default": "allow",
        "locked": true
      }
    ],
    "routes": [
      {
        "feature": "essentials",
        "path": "^/(?:sign-?in|sign-?up|account|settings|subscriptions|redirect|app-link|verify|logout|email-login|profile/edit)(?:/.*)?$"
      },
      {
        "feature": "content",
        "path": "^/(?:@[^/]+/)?note/[cp]-[0-9]+$"
      },
      {
        "feature": "content",
        "path": "^/@[^/]+/p-[0-9]+$"
      },
      {
        "feature": "content",
        "path": "^/(?:home|inbox)/post/(?:p-)?[0-9]+$"
      },
      {
        "feature": "content",
        "path": "^/pub/[^/]+/p/[^/]+$"
      },
      {
        "feature": "inbox",
        "path": "^/inbox(?:/.*)?$"
      },
      {
        "feature": "messages",
        "path": "^/(?:chat|messages)(?:/.*)?$"
      },
      {
        "feature": "notifications",
        "path": "^/activity(?:/.*)?$"
      },
      {
        "feature": "search",
        "path": "^/search(?:/.*)?$"
      },
      {
        "feature": "profiles",
        "path": "^/(?:@[^/]+|profile/[^/]+)(?:/.*)?$"
      },
      {
        "feature": "feed"
      }
    ],
    "fallbackFeature": "publications",
    "elements": [
      {
        "feature": "feed",
        "selector": "main.reader-nav-page",
        "on": [
          "feed"
        ]
      },
      {
        "feature": "recommendations",
        "selector": ".reader2-inbox-sidebar, [class*=\"exploreSidebar-\"]",
        "on": [
          "feed",
          "content",
          "inbox",
          "notifications",
          "search",
          "profiles"
        ]
      },
      {
        "feature": "recommendations",
        "selector": ".homepage-recommendations, .homepage-recommendations-view-all",
        "on": [
          "publications"
        ]
      },
      {
        "feature": "content",
        "selector": "main.reader-nav-page",
        "on": [
          "content"
        ]
      },
      {
        "feature": "publications",
        "selector": "#main",
        "on": [
          "publications"
        ]
      },
      {
        "feature": "inbox",
        "selector": "main.reader-nav-page",
        "on": [
          "inbox"
        ]
      },
      {
        "feature": "messages",
        "selector": "main.reader-nav-page",
        "on": [
          "messages"
        ]
      },
      {
        "feature": "notifications",
        "selector": "main.reader-nav-page",
        "on": [
          "notifications"
        ]
      },
      {
        "feature": "search",
        "selector": "main.reader-nav-page",
        "on": [
          "search"
        ]
      },
      {
        "feature": "profiles",
        "selector": "main.reader-nav-page",
        "on": [
          "profiles"
        ]
      }
    ]
  }
};
