//! DNS helpers and dnsmasq-style runtime configuration for Linux.
//!
//! The Linux backend still uses nftables as the packet-level backstop, but while focus is active
//! we also write a dnsmasq config that sinkholes policy-blocked names at DNS lookup time. The pure
//! wire helpers are retained for any future packet-DNS layer.

use std::collections::BTreeSet;
use std::fmt::Write as _;
use std::path::Path;
use std::process::Command;
use std::sync::Arc;
use std::time::Duration;

use crate::enforce::EnforceShared;
use crate::model::{Mode, Policy};

pub(crate) const RUNTIME_CONFIG_PATH: &str = "/run/talysman/dnsmasq.conf";
pub(crate) const DNSMASQ_INCLUDE_PATH: &str = "/etc/dnsmasq.d/talysman.conf";
const POLL: Duration = Duration::from_millis(250);

pub fn run_manager(shared: Arc<EnforceShared>, shutdown: tokio::sync::watch::Receiver<bool>) {
    let mut installed_gen: Option<u64> = None;
    let mut cleared_inactive = false;
    while !*shutdown.borrow() {
        if !shared.is_active() {
            if installed_gen.take().is_some() || !cleared_inactive {
                if let Err(e) = remove_config() {
                    tracing::warn!("failed to remove dnsmasq sinkhole config: {e}");
                } else {
                    tracing::info!("dnsmasq sinkhole removed (focus off)");
                }
                cleared_inactive = true;
            }
            std::thread::sleep(POLL);
            continue;
        }
        cleared_inactive = false;

        let gen = shared.generation();
        if installed_gen != Some(gen) {
            let policy = shared.policy_snapshot();
            match apply_policy(&policy) {
                Ok(()) => {
                    installed_gen = Some(gen);
                    tracing::info!("dnsmasq sinkhole applied for {:?}", policy.mode);
                }
                Err(e) => tracing::warn!("failed to apply dnsmasq sinkhole config: {e}"),
            }
        }
        std::thread::sleep(POLL);
    }
}

/// Write the permanent dnsmasq include that points at Talysman's runtime config. This is best
/// effort: systems without dnsmasq keep nftables enforcement, and the warning explains the gap.
pub fn install_include() -> std::io::Result<()> {
    std::fs::create_dir_all("/etc/dnsmasq.d")?;
    std::fs::write(
        DNSMASQ_INCLUDE_PATH,
        format!(
            "# Talysman DNS sinkhole include. Generated by talysman-svcctl.\nconf-file={RUNTIME_CONFIG_PATH}\n"
        ),
    )
}

pub fn remove_include() {
    let _ = std::fs::remove_file(DNSMASQ_INCLUDE_PATH);
}

pub fn apply_policy(policy: &Policy) -> std::io::Result<()> {
    if policy.mode == Mode::Blacklist && policy.domains.is_empty() {
        return remove_config();
    }

    if let Some(parent) = Path::new(RUNTIME_CONFIG_PATH).parent() {
        std::fs::create_dir_all(parent)?;
    }
    std::fs::write(RUNTIME_CONFIG_PATH, dnsmasq_config(policy))?;
    reload_dnsmasq();
    Ok(())
}

pub fn remove_config() -> std::io::Result<()> {
    match std::fs::remove_file(RUNTIME_CONFIG_PATH) {
        Ok(()) => {}
        Err(e) if e.kind() == std::io::ErrorKind::NotFound => {}
        Err(e) => return Err(e),
    }
    reload_dnsmasq();
    Ok(())
}

fn reload_dnsmasq() {
    if command_ok("systemctl", &["reload", "dnsmasq"]) {
        return;
    }
    if command_ok("pkill", &["-HUP", "dnsmasq"]) {
        return;
    }
    tracing::warn!("dnsmasq reload failed or dnsmasq is not running; DNS sinkhole is inactive");
}

fn command_ok(program: &str, args: &[&str]) -> bool {
    Command::new(program)
        .args(args)
        .status()
        .map(|s| s.success())
        .unwrap_or(false)
}

fn dnsmasq_config(policy: &Policy) -> String {
    let mut out = String::from(
        "# Talysman DNS sinkhole configuration.\n# Auto-generated; do not edit manually.\n\n",
    );

    match policy.mode {
        Mode::Blacklist => {
            for domain in dnsmasq_domains(&policy.domains) {
                let _ = writeln!(out, "address=/{domain}/0.0.0.0");
                let _ = writeln!(out, "address=/{domain}/::");
            }
        }
        Mode::Whitelist | Mode::BlockAll => {
            out.push_str("# Whitelist and block-all are enforced by nftables IP rules.\n");
        }
    }

    out
}

fn dnsmasq_domains(domains: &[String]) -> Vec<String> {
    let mut unique = BTreeSet::new();
    for domain in domains {
        let domain = domain
            .trim()
            .trim_start_matches("*.")
            .trim_end_matches('.')
            .to_ascii_lowercase();
        if !domain.is_empty() {
            unique.insert(domain);
        }
    }
    unique.into_iter().collect()
}

/// Parse the QNAME from a DNS query. Returns (name, offset_just_past_question).
pub(crate) fn read_qname(buf: &[u8]) -> Option<(String, usize)> {
    if buf.len() < 12 {
        return None;
    }
    let mut pos = 12; // skip the 12-byte header
    let mut labels = Vec::new();
    loop {
        let len = *buf.get(pos)? as usize;
        pos += 1;
        if len == 0 {
            break;
        }
        if len & 0xC0 != 0 {
            return None; // compression pointers don't appear in questions
        }
        let end = pos + len;
        let label = buf.get(pos..end)?;
        labels.push(String::from_utf8_lossy(label).to_string());
        pos = end;
    }
    // QTYPE (2) + QCLASS (2) follow the QNAME.
    let after = pos + 4;
    if after > buf.len() {
        return None;
    }
    Some((labels.join("."), after))
}

/// Build an NXDOMAIN reply payload from a query: keep the question, flip QR + RA, set RCODE=3,
/// zero the answer/authority/additional counts (this also drops any EDNS OPT record).
pub(crate) fn nxdomain_reply(query: &[u8], question_end: usize) -> Vec<u8> {
    let mut reply = query[..question_end].to_vec();
    reply[2] = 0x81; // QR=1, RD=1
    reply[3] = 0x83; // RA=1, RCODE=3 (NXDOMAIN)
    for i in 6..12 {
        reply[i] = 0; // ANCOUNT/NSCOUNT/ARCOUNT = 0
    }
    reply
}

/// Build a NODATA reply (NOERROR, no answers) — "the name exists but has no record of this
/// type". Used to suppress `HTTPS`/`SVCB` (type 65/64) records while focus is active so a browser
/// does not skip the plain A/AAAA lookup path with address hints or ECH metadata.
pub(crate) fn nodata_reply(query: &[u8], question_end: usize) -> Vec<u8> {
    let mut reply = query[..question_end].to_vec();
    reply[2] = 0x81; // QR=1, RD=1
    reply[3] = 0x80; // RA=1, RCODE=0 (NOERROR)
    for i in 6..12 {
        reply[i] = 0; // ANCOUNT/NSCOUNT/ARCOUNT = 0
    }
    reply
}

/// The QTYPE of a parsed query (the 2 bytes just before `question_end`, which `read_qname`
/// returns as the offset past QTYPE+QCLASS).
pub(crate) fn qtype(query: &[u8], question_end: usize) -> Option<u16> {
    let hi = question_end.checked_sub(4)?;
    let b = query.get(hi..hi + 2)?;
    Some(u16::from_be_bytes([b[0], b[1]]))
}

/// DNS QTYPE for the `HTTPS` resource record (RFC 9460), which carries the ECH config.
pub(crate) const QTYPE_HTTPS: u16 = 65;
/// DNS QTYPE for the generic `SVCB` resource record (RFC 9460).
pub(crate) const QTYPE_SVCB: u16 = 64;

#[cfg(test)]
mod tests {
    use super::*;
    use crate::model::Policy;

    #[test]
    fn reads_qname_and_offset() {
        // header (12) + "reddit.com" + QTYPE/QCLASS
        let mut q = vec![0x12, 0x34, 0x01, 0x00, 0, 1, 0, 0, 0, 0, 0, 0];
        q.extend_from_slice(&[6, b'r', b'e', b'd', b'd', b'i', b't']);
        q.extend_from_slice(&[3, b'c', b'o', b'm', 0]);
        q.extend_from_slice(&[0, 1, 0, 1]); // QTYPE=A, QCLASS=IN
        let (name, end) = read_qname(&q).unwrap();
        assert_eq!(name, "reddit.com");
        assert_eq!(end, q.len());
    }

    #[test]
    fn nxdomain_sets_flags_and_truncates() {
        let mut q = vec![0xab, 0xcd, 0x01, 0x00, 0, 1, 0, 0, 0, 0, 0, 1];
        q.extend_from_slice(&[3, b'x', b'y', b'z', 0, 0, 1, 0, 1]);
        let end = q.len();
        let reply = nxdomain_reply(&q, end);
        assert_eq!(reply[2], 0x81);
        assert_eq!(reply[3], 0x83);
        assert_eq!(&reply[6..12], &[0, 0, 0, 0, 0, 0]); // counts zeroed
        assert_eq!(reply[0], 0xab); // txn id preserved
    }

    #[test]
    fn nodata_is_noerror_with_no_answers() {
        let mut q = vec![0x11, 0x22, 0x01, 0x00, 0, 1, 0, 0, 0, 0, 0, 0];
        q.extend_from_slice(&[3, b'a', b'b', b'c', 0, 0, 65, 0, 1]); // QTYPE=HTTPS(65)
        let end = q.len();
        let reply = nodata_reply(&q, end);
        assert_eq!(reply[2], 0x81);
        assert_eq!(reply[3], 0x80); // RCODE 0
        assert_eq!(&reply[6..12], &[0, 0, 0, 0, 0, 0]);
        assert_eq!(reply[0], 0x11);
    }

    #[test]
    fn reads_qtype() {
        // header(12) + "a"(label) + root + QTYPE=65 + QCLASS=1
        let mut q = vec![0, 0, 0x01, 0x00, 0, 1, 0, 0, 0, 0, 0, 0];
        q.extend_from_slice(&[1, b'a', 0, 0, 65, 0, 1]);
        let (_name, end) = read_qname(&q).unwrap();
        assert_eq!(qtype(&q, end), Some(QTYPE_HTTPS));
    }

    #[test]
    fn dnsmasq_config_sinkholes_blacklist_domains() {
        let mut p = Policy::default();
        p.domains = vec![
            "YouTube.com".into(),
            "*.reddit.com".into(),
            "youtube.com.".into(),
        ];
        let config = dnsmasq_config(&p);
        assert!(config.contains("address=/youtube.com/0.0.0.0"));
        assert!(config.contains("address=/youtube.com/::"));
        assert!(config.contains("address=/reddit.com/0.0.0.0"));
        assert_eq!(config.matches("address=/youtube.com/0.0.0.0").count(), 1);
    }

    #[test]
    fn dnsmasq_config_does_not_try_to_encode_whitelist() {
        let mut p = Policy::default();
        p.mode = crate::model::Mode::Whitelist;
        p.domains = vec!["example.com".into()];
        let config = dnsmasq_config(&p);
        assert!(!config.contains("address=/example.com/0.0.0.0"));
        assert!(config.contains("enforced by nftables"));
    }
}
