//! DNS helpers and dnsmasq-style runtime configuration for Linux.
//!
//! The Linux backend still uses nftables as the packet-level backstop, but while focus is active
//! we also write a dnsmasq config that sinkholes policy-blocked names at DNS lookup time.

use std::collections::BTreeSet;
use std::fmt::Write as _;
use std::path::Path;
use std::process::Command;
use std::sync::Arc;
use std::time::Duration;

use crate::enforce::EnforceShared;
use crate::model::Policy;

pub(crate) const RUNTIME_CONFIG_PATH: &str = "/run/talysman/dnsmasq.conf";
pub(crate) const DNSMASQ_INCLUDE_PATH: &str = "/etc/dnsmasq.d/talysman.conf";
const IDLE_WAIT: Duration = Duration::from_secs(60 * 60);
const RETRY_WAIT: Duration = Duration::from_secs(5);

pub fn run_manager(shared: Arc<EnforceShared>, shutdown: tokio::sync::watch::Receiver<bool>) {
    let mut installed_gen: Option<u64> = None;
    let mut cleared_inactive = false;
    let mut observed = shared.change_generation();
    while !*shutdown.borrow() {
        if !shared.is_active() {
            if installed_gen.take().is_some() || !cleared_inactive {
                if let Err(e) = remove_config() {
                    tracing::warn!("failed to remove dnsmasq sinkhole config: {e}");
                } else {
                    tracing::info!("dnsmasq sinkhole removed (focus off)");
                }
                cleared_inactive = true;
            }
            observed = shared.wait_for_change(observed, IDLE_WAIT);
            continue;
        }
        cleared_inactive = false;

        let gen = shared.generation();
        if installed_gen != Some(gen) {
            let policy = shared.policy_snapshot();
            match apply_policy(&policy) {
                Ok(()) => {
                    installed_gen = Some(gen);
                    tracing::info!(
                        "dnsmasq sinkhole applied for {} blocked domain(s)",
                        policy.blocked_domains.len()
                    );
                }
                Err(e) => tracing::warn!("failed to apply dnsmasq sinkhole config: {e}"),
            }
        }
        let wait = if installed_gen == Some(gen) {
            IDLE_WAIT
        } else {
            RETRY_WAIT
        };
        observed = shared.wait_for_change(observed, wait);
    }
}

/// Write the permanent dnsmasq include that points at Talysman's runtime config. This is best
/// effort: systems without dnsmasq keep nftables enforcement, and the warning explains the gap.
pub fn install_include() -> std::io::Result<()> {
    std::fs::create_dir_all("/etc/dnsmasq.d")?;
    std::fs::write(
        DNSMASQ_INCLUDE_PATH,
        format!(
            "# Talysman DNS sinkhole include. Generated by talysman-svcctl.\nconf-file={RUNTIME_CONFIG_PATH}\n"
        ),
    )
}

pub fn remove_include() {
    let _ = std::fs::remove_file(DNSMASQ_INCLUDE_PATH);
}

/// dnsmasq only ever sinkholes `blockedDomains` — the hard block list. `allowedDomains` exemptions
/// and the `defaultAction` fallback for everything else are enforced at the IP/port level by
/// nftables (see `nft.rs`).
pub fn apply_policy(policy: &Policy) -> std::io::Result<()> {
    if policy.blocked_domains.is_empty() {
        return remove_config();
    }

    if let Some(parent) = Path::new(RUNTIME_CONFIG_PATH).parent() {
        std::fs::create_dir_all(parent)?;
    }
    std::fs::write(RUNTIME_CONFIG_PATH, dnsmasq_config(policy))?;
    reload_dnsmasq();
    Ok(())
}

pub fn remove_config() -> std::io::Result<()> {
    match std::fs::remove_file(RUNTIME_CONFIG_PATH) {
        Ok(()) => {}
        Err(e) if e.kind() == std::io::ErrorKind::NotFound => {}
        Err(e) => return Err(e),
    }
    reload_dnsmasq();
    Ok(())
}

fn reload_dnsmasq() {
    if command_ok("systemctl", &["reload", "dnsmasq"]) {
        return;
    }
    if command_ok("pkill", &["-HUP", "dnsmasq"]) {
        return;
    }
    tracing::warn!("dnsmasq reload failed or dnsmasq is not running; DNS sinkhole is inactive");
}

fn command_ok(program: &str, args: &[&str]) -> bool {
    Command::new(program)
        .args(args)
        .status()
        .map(|s| s.success())
        .unwrap_or(false)
}

fn dnsmasq_config(policy: &Policy) -> String {
    let mut out = String::from(
        "# Talysman DNS sinkhole configuration.\n# Auto-generated; do not edit manually.\n\n",
    );

    if policy.blocked_domains.is_empty() {
        out.push_str("# No explicit blocked domains; enforced by nftables IP rules.\n");
    } else {
        for domain in dnsmasq_domains(&policy.blocked_domains) {
            let _ = writeln!(out, "address=/{domain}/0.0.0.0");
            let _ = writeln!(out, "address=/{domain}/::");
        }
    }

    out
}

fn dnsmasq_domains(domains: &[String]) -> Vec<String> {
    let mut unique = BTreeSet::new();
    for domain in domains {
        let domain = domain
            .trim()
            .trim_start_matches("*.")
            .trim_end_matches('.')
            .to_ascii_lowercase();
        if !domain.is_empty() {
            unique.insert(domain);
        }
    }
    unique.into_iter().collect()
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::model::Policy;

    #[test]
    fn dnsmasq_config_sinkholes_blocked_domains() {
        let mut p = Policy::default();
        p.blocked_domains = vec![
            "YouTube.com".into(),
            "*.reddit.com".into(),
            "youtube.com.".into(),
        ];
        let config = dnsmasq_config(&p);
        assert!(config.contains("address=/youtube.com/0.0.0.0"));
        assert!(config.contains("address=/youtube.com/::"));
        assert!(config.contains("address=/reddit.com/0.0.0.0"));
        assert_eq!(config.matches("address=/youtube.com/0.0.0.0").count(), 1);
    }

    #[test]
    fn dnsmasq_config_does_not_try_to_encode_allowed_domains() {
        let mut p = Policy::default();
        p.default_action = crate::model::DefaultAction::Block;
        p.allowed_domains = vec!["example.com".into()];
        let config = dnsmasq_config(&p);
        assert!(!config.contains("address=/example.com/0.0.0.0"));
        assert!(config.contains("enforced by nftables"));
    }
}
